<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Document definition -->
<!DOCTYPE MEME [
<!ELEMENT MEME (training_set , model , motifs , scanned_sites_summary?)>
<!ATTLIST MEME version CDATA #REQUIRED>
<!ATTLIST MEME release CDATA #REQUIRED>
<!-- Training-set elements --><!ELEMENT training_set (alphabet , ambigs , sequence* , letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED>
<!ATTLIST training_set primary_count CDATA #REQUIRED>
<!ATTLIST training_set primary_positions CDATA #REQUIRED>
<!ATTLIST training_set control_sequences CDATA "">
<!ATTLIST training_set control_count CDATA "">
<!ATTLIST training_set control_positions CDATA "">
<!ELEMENT alphabet (letter)*>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter)*>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED>
<!ATTLIST sequence name CDATA #REQUIRED>
<!ATTLIST sequence length CDATA #REQUIRED>
<!ATTLIST sequence weight CDATA #REQUIRED>
<!ELEMENT letter_frequencies (alphabet_array)>
<!-- Model elements --><!ELEMENT model (command_line , host , type , nmotifs , evalue_threshold , object_function , spfun , min_width , max_width , wg , ws , endgaps , minsites , maxsites , wnsites , spmap , spfuzz , prior , beta , maxiter , distance , num_positions , seed , hsfrac , searchsize , maxsize , norand , csites , strands , brief , psp_file , priors_file , reason_for_stopping , background_frequencies)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>
<!ATTLIST background_frequencies order CDATA #REQUIRED>
<!-- Motif elements --><!ELEMENT motifs (motif)*>
<!ELEMENT motif (scores , probabilities , regular_expression? , contributing_sites)>
<!ATTLIST motif id ID #REQUIRED>
<!ATTLIST motif name CDATA #REQUIRED>
<!ATTLIST motif alt CDATA "">
<!ATTLIST motif width CDATA #REQUIRED>
<!ATTLIST motif sites CDATA #REQUIRED>
<!ATTLIST motif ic CDATA #REQUIRED>
<!ATTLIST motif re CDATA #REQUIRED>
<!ATTLIST motif llr CDATA #REQUIRED>
<!ATTLIST motif p_value CDATA #REQUIRED>
<!ATTLIST motif e_value CDATA #REQUIRED>
<!ATTLIST motif bayes_threshold CDATA #REQUIRED>
<!ATTLIST motif elapsed_time CDATA #REQUIRED>
<!ATTLIST motif url CDATA "">
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>
<!-- Contributing site elements --><!-- Contributing sites are motif occurences found during the motif discovery phase --><!ELEMENT contributing_sites (contributing_site)*>
<!ELEMENT contributing_site (left_flank , site , right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED>
<!ATTLIST contributing_site position CDATA #REQUIRED>
<!ATTLIST contributing_site strand (plus | minus | none) "none">
<!ATTLIST contributing_site pvalue CDATA #REQUIRED>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start --><!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance --><!ELEMENT site (letter_ref)*>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end --><!ELEMENT right_flank (#PCDATA)>
<!-- Scanned site elements --><!-- Scanned sites are motif occurences found during the sequence scan phase --><!ELEMENT scanned_sites_summary (scanned_sites)*>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site)*>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED>
<!ATTLIST scanned_sites pvalue CDATA #REQUIRED>
<!ATTLIST scanned_sites num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site motif_id IDREF #REQUIRED>
<!ATTLIST scanned_site strand (plus | minus | none) "none">
<!ATTLIST scanned_site position CDATA #REQUIRED>
<!ATTLIST scanned_site pvalue CDATA #REQUIRED>
<!-- Utility elements --><!-- A reference to a letter in the alphabet --><!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet --><!ELEMENT alphabet_array (value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>
<!-- A alphabet_matrix contains one alphabet_array for each position in a motif --><!ELEMENT alphabet_matrix (alphabet_array)*>
]>
<!-- Begin document body -->
<MEME version="5.5.5" release="Thu Sep 14 08:48:04 2023 +1000">
  <training_set primary_sequences="data/tmp_memedir/FALSE_TRUE_TRUE_2sd_QNZS_C4_FALSE_53_39/RORB.fasta" primary_count="296064" primary_positions="11826845" control_sequences="--none--" control_count="0" control_positions="0">
    <alphabet name="DNA" like="dna">
      <letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
      <letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
      <letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
      <letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
      <letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
      <letter id="V" symbol="V" equals="ACG" name="Not T"/>
      <letter id="H" symbol="H" equals="ACT" name="Not G"/>
      <letter id="D" symbol="D" equals="AGT" name="Not C"/>
      <letter id="B" symbol="B" equals="CGT" name="Not A"/>
      <letter id="M" symbol="M" equals="AC" name="Amino"/>
      <letter id="R" symbol="R" equals="AG" name="Purine"/>
      <letter id="W" symbol="W" equals="AT" name="Weak"/>
      <letter id="S" symbol="S" equals="CG" name="Strong"/>
      <letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
      <letter id="K" symbol="K" equals="GT" name="Keto"/>
    </alphabet>
    <letter_frequencies>
      <alphabet_array>
        <value letter_id="A">0.19</value>
        <value letter_id="C">0.187</value>
        <value letter_id="G">0.383</value>
        <value letter_id="T">0.239</value>
      </alphabet_array>
    </letter_frequencies>
  </training_set>
  <model>
    <command_line>meme data/tmp_memedir/FALSE_TRUE_TRUE_2sd_QNZS_C4_FALSE_53_39/RORB.fasta -oc data/tmp_memedir/FALSE_TRUE_TRUE_2sd_QNZS_C4_FALSE_53_39/RORB -nmotifs 6 -dna -maxw 30 -p 7 -seed 53 </command_line>
    <host>ip-172-31-25-197</host>
    <type>zoops</type>
    <nmotifs>6</nmotifs>
    <evalue_threshold>inf</evalue_threshold>
    <object_function>E-value of product of p-values</object_function>
    <spfun>E-value of product of p-values</spfun>
    <min_width>8</min_width>
    <max_width>30</max_width>
    <wg>11</wg>
    <ws>1</ws>
    <endgaps>yes</endgaps>
    <substring>yes</substring>
    <minsites>2</minsites>
    <maxsites>296064</maxsites>
    <wnsites>0.8</wnsites>
    <spmap>uni</spmap>
    <spfuzz>0.5</spfuzz>
    <prior>dirichlet</prior>
    <beta>0.01</beta>
    <maxiter>50</maxiter>
    <distance>1e-05</distance>
    <num_positions>11826845</num_positions>
    <seed>53</seed>
    <hsfrac>0</hsfrac>
    <searchsize>100000</searchsize>
    <maxsize>0</maxsize>
    <norand>no</norand>
    <csites>1000</csites>
    <strands>forward</strands>
    <brief>1000</brief>
    <psp_file/>
    <priors_file/>
    <reason_for_stopping>Stopped because requested number of motifs (6) found.</reason_for_stopping>
    <background_frequencies source="--sequences--" order="0">
      <alphabet_array>
        <value letter_id="A">0.19</value>
        <value letter_id="C">0.187</value>
        <value letter_id="G">0.383</value>
        <value letter_id="T">0.239</value>
      </alphabet_array>
    </background_frequencies>
  </model>
  <motifs>
    <motif id="motif_1" name="AWGTAGGTCAN" alt="MEME-1" width="11" sites="71841" ic="15.5" re="15.9" llr="793950" p_value="3.6e-1131" e_value="5.3e-529" bayes_threshold="9.2465" elapsed_time="74.541725">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">233</value>
            <value letter_id="C">-420</value>
            <value letter_id="G">-2278</value>
            <value letter_id="T">-270</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">169</value>
            <value letter_id="C">-2278</value>
            <value letter_id="G">-736</value>
            <value letter_id="T">69</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-157</value>
            <value letter_id="C">35</value>
            <value letter_id="G">36</value>
            <value letter_id="T">-23</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-550</value>
            <value letter_id="C">-380</value>
            <value letter_id="G">-291</value>
            <value letter_id="T">196</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">210</value>
            <value letter_id="C">-2278</value>
            <value letter_id="G">-104</value>
            <value letter_id="T">-2278</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2278</value>
            <value letter_id="C">-991</value>
            <value letter_id="G">138</value>
            <value letter_id="T">-652</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2278</value>
            <value letter_id="C">-2278</value>
            <value letter_id="G">138</value>
            <value letter_id="T">-2278</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-538</value>
            <value letter_id="C">-2278</value>
            <value letter_id="G">-567</value>
            <value letter_id="T">205</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2278</value>
            <value letter_id="C">240</value>
            <value letter_id="G">-809</value>
            <value letter_id="T">-471</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">235</value>
            <value letter_id="C">-2278</value>
            <value letter_id="G">-357</value>
            <value letter_id="T">-2278</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">22</value>
            <value letter_id="C">83</value>
            <value letter_id="G">-119</value>
            <value letter_id="T">20</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.952896</value>
            <value letter_id="C">0.010175</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.036929</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.612728</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.002325</value>
            <value letter_id="T">0.384947</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.063877</value>
            <value letter_id="C">0.238916</value>
            <value letter_id="G">0.493367</value>
            <value letter_id="T">0.203839</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.004190</value>
            <value letter_id="C">0.013488</value>
            <value letter_id="G">0.051085</value>
            <value letter_id="T">0.931237</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.814215</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.185785</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000195</value>
            <value letter_id="G">0.997202</value>
            <value letter_id="T">0.002603</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">1.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.004552</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.007544</value>
            <value letter_id="T">0.987904</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.989477</value>
            <value letter_id="G">0.001406</value>
            <value letter_id="T">0.009117</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.967651</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.032349</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.222060</value>
            <value letter_id="C">0.333807</value>
            <value letter_id="G">0.168288</value>
            <value letter_id="T">0.275845</value>
          </alphabet_array>
        </alphabet_matrix>
      </probabilities>
      <regular_expression>
A[AT][GCT]TAGGTCA[CTA]
</regular_expression>
      <contributing_sites/>
    </motif>
    <motif id="motif_2" name="TGACCTASTTW" alt="MEME-2" width="11" sites="41641" ic="16.0" re="17.5" llr="504042" p_value="7.2e-776" e_value="7.4e-359" bayes_threshold="10.0536" elapsed_time="123.046045">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">-2199</value>
            <value letter_id="C">-2199</value>
            <value letter_id="G">-2199</value>
            <value letter_id="T">206</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2199</value>
            <value letter_id="C">-2199</value>
            <value letter_id="G">138</value>
            <value letter_id="T">-2199</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">230</value>
            <value letter_id="C">-406</value>
            <value letter_id="G">-314</value>
            <value letter_id="T">-435</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2199</value>
            <value letter_id="C">242</value>
            <value letter_id="G">-2199</value>
            <value letter_id="T">-2199</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-628</value>
            <value letter_id="C">241</value>
            <value letter_id="G">-2199</value>
            <value letter_id="T">-2199</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2199</value>
            <value letter_id="C">-52</value>
            <value letter_id="G">-2199</value>
            <value letter_id="T">186</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">223</value>
            <value letter_id="C">-148</value>
            <value letter_id="G">-355</value>
            <value letter_id="T">-517</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-13</value>
            <value letter_id="C">93</value>
            <value letter_id="G">2</value>
            <value letter_id="T">-158</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">59</value>
            <value letter_id="C">-2199</value>
            <value letter_id="G">-2199</value>
            <value letter_id="T">158</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-400</value>
            <value letter_id="C">-597</value>
            <value letter_id="G">-2199</value>
            <value letter_id="T">204</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">87</value>
            <value letter_id="C">-100</value>
            <value letter_id="G">-263</value>
            <value letter_id="T">106</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">1.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">1.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.933719</value>
            <value letter_id="C">0.011215</value>
            <value letter_id="G">0.043347</value>
            <value letter_id="T">0.011719</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">1.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.002450</value>
            <value letter_id="C">0.997550</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.130448</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.869552</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.893662</value>
            <value letter_id="C">0.066929</value>
            <value letter_id="G">0.032756</value>
            <value letter_id="T">0.006652</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.174155</value>
            <value letter_id="C">0.357772</value>
            <value letter_id="G">0.387887</value>
            <value letter_id="T">0.080185</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.285680</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.714320</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.011863</value>
            <value letter_id="C">0.002978</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.985159</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.346630</value>
            <value letter_id="C">0.093682</value>
            <value letter_id="G">0.061982</value>
            <value letter_id="T">0.497707</value>
          </alphabet_array>
        </alphabet_matrix>
      </probabilities>
      <regular_expression>
TGACCTA[GC][TA]T[TA]
</regular_expression>
      <contributing_sites/>
    </motif>
    <motif id="motif_3" name="GGGGGGGGDGGGGGDGGNGGBGGGGGGGGG" alt="MEME-3" width="30" sites="30283" ic="18.8" re="9.8" llr="205807" p_value="1.9e-425" e_value="7.8e-066" bayes_threshold="9.04884" elapsed_time="171.351230">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">-161</value>
            <value letter_id="C">-109</value>
            <value letter_id="G">96</value>
            <value letter_id="T">-116</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-40</value>
            <value letter_id="C">-167</value>
            <value letter_id="G">82</value>
            <value letter_id="T">-99</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-252</value>
            <value letter_id="C">-87</value>
            <value letter_id="G">99</value>
            <value letter_id="T">-125</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-103</value>
            <value letter_id="C">-239</value>
            <value letter_id="G">88</value>
            <value letter_id="T">-51</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-27</value>
            <value letter_id="C">-51</value>
            <value letter_id="G">43</value>
            <value letter_id="T">-31</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-38</value>
            <value letter_id="C">-46</value>
            <value letter_id="G">57</value>
            <value letter_id="T">-68</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2153</value>
            <value letter_id="C">-129</value>
            <value letter_id="G">105</value>
            <value letter_id="T">-90</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-5</value>
            <value letter_id="C">-52</value>
            <value letter_id="G">52</value>
            <value letter_id="T">-83</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">37</value>
            <value letter_id="C">-69</value>
            <value letter_id="G">14</value>
            <value letter_id="T">-15</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-127</value>
            <value letter_id="C">-110</value>
            <value letter_id="G">109</value>
            <value letter_id="T">-393</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-2153</value>
            <value letter_id="C">-144</value>
            <value letter_id="G">123</value>
            <value letter_id="T">-287</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-53</value>
            <value letter_id="C">-2153</value>
            <value letter_id="G">86</value>
            <value letter_id="T">-48</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-101</value>
            <value letter_id="C">-815</value>
            <value letter_id="G">124</value>
            <value letter_id="T">-2153</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-391</value>
            <value letter_id="C">-36</value>
            <value letter_id="G">90</value>
            <value letter_id="T">-93</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">37</value>
            <value letter_id="C">-11</value>
            <value letter_id="G">-5</value>
            <value letter_id="T">-19</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-10</value>
            <value letter_id="C">21</value>
            <value letter_id="G">32</value>
            <value letter_id="T">-88</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-73</value>
            <value letter_id="C">-141</value>
            <value letter_id="G">79</value>
            <value letter_id="T">-64</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0</value>
            <value letter_id="C">24</value>
            <value letter_id="G">-14</value>
            <value letter_id="T">1</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-104</value>
            <value letter_id="C">7</value>
            <value letter_id="G">64</value>
            <value letter_id="T">-106</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">3</value>
            <value letter_id="C">-92</value>
            <value letter_id="G">55</value>
            <value letter_id="T">-70</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-36</value>
            <value letter_id="C">19</value>
            <value letter_id="G">10</value>
            <value letter_id="T">-8</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-9</value>
            <value letter_id="C">-2153</value>
            <value letter_id="G">85</value>
            <value letter_id="T">-87</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-179</value>
            <value letter_id="C">22</value>
            <value letter_id="G">85</value>
            <value letter_id="T">-272</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-40</value>
            <value letter_id="C">-278</value>
            <value letter_id="G">83</value>
            <value letter_id="T">-70</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-37</value>
            <value letter_id="C">-15</value>
            <value letter_id="G">45</value>
            <value letter_id="T">-58</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-111</value>
            <value letter_id="C">-340</value>
            <value letter_id="G">107</value>
            <value letter_id="T">-138</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-7</value>
            <value letter_id="C">-144</value>
            <value letter_id="G">74</value>
            <value letter_id="T">-113</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-62</value>
            <value letter_id="C">-123</value>
            <value letter_id="G">70</value>
            <value letter_id="T">-45</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-136</value>
            <value letter_id="C">-110</value>
            <value letter_id="G">113</value>
            <value letter_id="T">-2153</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-153</value>
            <value letter_id="C">-51</value>
            <value letter_id="G">86</value>
            <value letter_id="T">-118</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.062114</value>
            <value letter_id="C">0.087706</value>
            <value letter_id="G">0.743387</value>
            <value letter_id="T">0.106793</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.143678</value>
            <value letter_id="C">0.058713</value>
            <value letter_id="G">0.676683</value>
            <value letter_id="T">0.120926</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.033088</value>
            <value letter_id="C">0.102599</value>
            <value letter_id="G">0.763696</value>
            <value letter_id="T">0.100618</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.093353</value>
            <value letter_id="C">0.035697</value>
            <value letter_id="G">0.703134</value>
            <value letter_id="T">0.167817</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.158109</value>
            <value letter_id="C">0.131922</value>
            <value letter_id="G">0.516825</value>
            <value letter_id="T">0.193145</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.146155</value>
            <value letter_id="C">0.135984</value>
            <value letter_id="G">0.568735</value>
            <value letter_id="T">0.149127</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.076545</value>
            <value letter_id="G">0.795397</value>
            <value letter_id="T">0.128059</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.183601</value>
            <value letter_id="C">0.130172</value>