<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED primary_count CDATA #REQUIRED primary_positions CDATA #REQUIRED
  control_sequences CDATA "" control_count CDATA "" control_positions CDATA "">
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_positions,
  seed,
  hsfrac,
  searchsize,
  maxsize,
  norand,
  csites,
  strands,
  brief,
  psp_file,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED
		   order CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                llr CDATA #REQUIRED
                p_value CDATA #REQUIRED
                e_value CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="5.5.5" release="Thu Sep 14 08:48:04 2023 +1000">
<training_set primary_sequences="data/tmp_memedir/NA_FALSE_TRUE_TRUE_25_30_53_126/ZNF251.fasta" primary_count="10071" primary_positions="1218591" control_sequences="--none--" control_count="0" control_positions="0">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.28</value>
<value letter_id="C">0.22</value>
<value letter_id="G">0.22</value>
<value letter_id="T">0.28</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme data/tmp_memedir/NA_FALSE_TRUE_TRUE_25_30_53_126/ZNF251.fasta -oc data/tmp_memedir/NA_FALSE_TRUE_TRUE_25_30_53_126/ZNF251 -nmotifs 6 -dna -maxw 30 -p 3 -seed 53 -revcomp </command_line>
<host>fedora</host>
<type>zoops</type>
<nmotifs>6</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<spfun>E-value of product of p-values</spfun>
<min_width>8</min_width>
<max_width>30</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>10071</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_positions>1218591</num_positions>
<seed>53</seed>
<hsfrac>0</hsfrac>
<searchsize>100000</searchsize>
<maxsize>0</maxsize>
<norand>no</norand>
<csites>1000</csites>
<strands>both</strands>
<brief>1000</brief>
<psp_file></psp_file>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (6) found.</reason_for_stopping>
<background_frequencies source="--sequences--" order="0">
<alphabet_array>
<value letter_id="A">0.28</value>
<value letter_id="C">0.22</value>
<value letter_id="G">0.22</value>
<value letter_id="T">0.28</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="GYTAAGTGAAAKAAGCC" alt="MEME-1" width="17" sites="4506" ic="27.2" re="26.8" llr="83801" p_value="6.4e-2937" e_value="2.1e-1817" bayes_threshold="10.1749" elapsed_time="222.788538">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-447</value>
<value letter_id="C">-1878</value>
<value letter_id="G">217</value>
<value letter_id="T">-1878</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1878</value>
<value letter_id="C">149</value>
<value letter_id="G">-1878</value>
<value letter_id="T">45</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-566</value>
<value letter_id="C">-402</value>
<value letter_id="G">-1878</value>
<value letter_id="T">181</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">176</value>
<value letter_id="C">-525</value>
<value letter_id="G">-254</value>
<value letter_id="T">-488</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">183</value>
<value letter_id="C">-1878</value>
<value letter_id="G">-795</value>
<value letter_id="T">-1878</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-285</value>
<value letter_id="C">-1878</value>
<value letter_id="G">213</value>
<value letter_id="T">-1878</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-509</value>
<value letter_id="C">-290</value>
<value letter_id="G">-414</value>
<value letter_id="T">176</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-400</value>
<value letter_id="C">-1878</value>
<value letter_id="G">216</value>
<value letter_id="T">-1878</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">181</value>
<value letter_id="C">-425</value>
<value letter_id="G">-514</value>
<value letter_id="T">-1878</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">179</value>
<value letter_id="C">-1878</value>
<value letter_id="G">-282</value>
<value letter_id="T">-1878</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">182</value>
<value letter_id="C">-1878</value>
<value letter_id="G">-466</value>
<value letter_id="T">-830</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-132</value>
<value letter_id="C">-127</value>
<value letter_id="G">90</value>
<value letter_id="T">46</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">178</value>
<value letter_id="C">-556</value>
<value letter_id="G">-309</value>
<value letter_id="T">-530</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">174</value>
<value letter_id="C">-459</value>
<value letter_id="G">-262</value>
<value letter_id="T">-406</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-195</value>
<value letter_id="C">-1878</value>
<value letter_id="G">208</value>
<value letter_id="T">-1878</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-469</value>
<value letter_id="C">204</value>
<value letter_id="G">-318</value>
<value letter_id="T">-218</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-248</value>
<value letter_id="C">198</value>
<value letter_id="G">-531</value>
<value letter_id="T">-188</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.012650</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.987350</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.616511</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.383489</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.005548</value>
<value letter_id="C">0.013538</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.980914</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.946960</value>
<value letter_id="C">0.005770</value>
<value letter_id="G">0.037727</value>
<value letter_id="T">0.009543</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.999112</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000888</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.038837</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.961163</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.008211</value>
<value letter_id="C">0.029516</value>
<value letter_id="G">0.012428</value>
<value letter_id="T">0.949845</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.017532</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.982468</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.982246</value>
<value letter_id="C">0.011540</value>
<value letter_id="G">0.006214</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.968930</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.031070</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.990457</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.008655</value>
<value letter_id="T">0.000888</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.112517</value>
<value letter_id="C">0.090768</value>
<value letter_id="G">0.409898</value>
<value letter_id="T">0.386818</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.962494</value>
<value letter_id="C">0.004660</value>
<value letter_id="G">0.025743</value>
<value letter_id="T">0.007102</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.938304</value>
<value letter_id="C">0.009099</value>
<value letter_id="G">0.035730</value>
<value letter_id="T">0.016866</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.072792</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.927208</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.010874</value>
<value letter_id="C">0.903018</value>
<value letter_id="G">0.024190</value>
<value letter_id="T">0.061917</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.050155</value>
<value letter_id="C">0.868176</value>
<value letter_id="G">0.005548</value>
<value letter_id="T">0.076121</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
G[CT]TAAGTGAAA[GT]AAGCC
</regular_expression>
<contributing_sites>
</contributing_sites>
</motif>
<motif id="motif_2" name="ACAACATGGATGAACCT" alt="MEME-2" width="17" sites="2522" ic="21.8" re="21.4" llr="37406" p_value="7.6e-1568" e_value="6.4e-661" bayes_threshold="9.82322" elapsed_time="409.490613">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">147</value>
<value letter_id="C">-465</value>
<value letter_id="G">-12</value>
<value letter_id="T">-426</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-177</value>
<value letter_id="C">192</value>
<value letter_id="G">-387</value>
<value letter_id="T">-193</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">166</value>
<value letter_id="C">-298</value>
<value letter_id="G">-167</value>
<value letter_id="T">-407</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">171</value>
<value letter_id="C">-416</value>
<value letter_id="G">-176</value>
<value letter_id="T">-547</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-332</value>
<value letter_id="C">196</value>
<value letter_id="G">-394</value>
<value letter_id="T">-142</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">166</value>
<value letter_id="C">-365</value>
<value letter_id="G">-152</value>
<value letter_id="T">-401</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-388</value>
<value letter_id="C">-189</value>
<value letter_id="G">-372</value>
<value letter_id="T">169</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-132</value>
<value letter_id="C">-753</value>
<value letter_id="G">199</value>
<value letter_id="T">-451</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-122</value>
<value letter_id="C">-350</value>
<value letter_id="G">195</value>
<value letter_id="T">-482</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">170</value>
<value letter_id="C">-365</value>
<value letter_id="G">-180</value>
<value letter_id="T">-501</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-314</value>
<value letter_id="C">-323</value>
<value letter_id="G">-208</value>
<value letter_id="T">167</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-101</value>
<value letter_id="C">-594</value>
<value letter_id="G">194</value>
<value letter_id="T">-447</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">143</value>
<value letter_id="C">-372</value>
<value letter_id="G">0</value>
<value letter_id="T">-471</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">170</value>
<value letter_id="C">-359</value>
<value letter_id="G">-176</value>
<value letter_id="T">-538</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-18</value>
<value letter_id="C">142</value>
<value letter_id="G">-272</value>
<value letter_id="T">-110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-466</value>
<value letter_id="C">204</value>
<value letter_id="G">-416</value>
<value letter_id="T">-189</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-404</value>
<value letter_id="C">-199</value>
<value letter_id="G">-511</value>
<value letter_id="T">172</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.774385</value>
<value letter_id="C">0.008723</value>
<value letter_id="G">0.202220</value>
<value letter_id="T">0.014671</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.082474</value>
<value letter_id="C">0.828707</value>
<value letter_id="G">0.015067</value>
<value letter_id="T">0.073751</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.886598</value>
<value letter_id="C">0.027756</value>
<value letter_id="G">0.068993</value>
<value letter_id="T">0.016653</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.916336</value>
<value letter_id="C">0.012292</value>
<value letter_id="G">0.065028</value>
<value letter_id="T">0.006344</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.028152</value>
<value letter_id="C">0.852498</value>
<value letter_id="G">0.014274</value>
<value letter_id="T">0.105075</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.888580</value>
<value letter_id="C">0.017446</value>
<value letter_id="G">0.076527</value>
<value letter_id="T">0.017446</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.019033</value>
<value letter_id="C">0.059080</value>
<value letter_id="G">0.016653</value>
<value letter_id="T">0.905234</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.112213</value>
<value letter_id="C">0.001190</value>
<value letter_id="G">0.874306</value>
<value letter_id="T">0.012292</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.120143</value>
<value letter_id="C">0.019429</value>
<value letter_id="G">0.850515</value>
<value letter_id="T">0.009913</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.910785</value>
<value letter_id="C">0.017446</value>
<value letter_id="G">0.063045</value>
<value letter_id="T">0.008723</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.031721</value>
<value letter_id="C">0.023394</value>
<value letter_id="G">0.051943</value>
<value letter_id="T">0.892942</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.139175</value>
<value letter_id="C">0.003569</value>
<value letter_id="G">0.844568</value>
<value letter_id="T">0.012688</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.753370</value>
<value letter_id="C">0.016653</value>
<value letter_id="G">0.219270</value>
<value letter_id="T">0.010706</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.909992</value>
<value letter_id="C">0.018239</value>
<value letter_id="G">0.065028</value>
<value letter_id="T">0.006741</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.247423</value>
<value letter_id="C">0.588422</value>
<value letter_id="G">0.033307</value>
<value letter_id="T">0.130849</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.011102</value>
<value letter_id="C">0.900872</value>
<value letter_id="G">0.012292</value>
<value letter_id="T">0.075734</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.017050</value>
<value letter_id="C">0.055115</value>
<value letter_id="G">0.006344</value>
<value letter_id="T">0.921491</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[AG]CAACATGGATG[AG]A[CA]CT
</regular_expression>
<contributing_sites>
</contributing_sites>
</motif>
<motif id="motif_3" name="RTGRRATCATRCARTATKTG" alt="MEME-3" width="20" sites="1872" ic="23.2" re="22.3" llr="28955" p_value="8.6e-1324" e_value="3.5e-563" bayes_threshold="10.3545" elapsed_time="588.169850">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">41</value>
<value letter_id="C">-344</value>
<value letter_id="G">126</value>
<value letter_id="T">-179</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-361</value>
<value letter_id="C">-393</value>
<value letter_id="G">-383</value>
<value letter_id="T">176</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-132</value>
<value letter_id="C">-868</value>
<value letter_id="G">198</value>
<value letter_id="T">-368</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">63</value>
<value letter_id="C">-360</value>
<value letter_id="G">130</value>
<value letter_id="T">-534</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">117</value>
<value letter_id="C">-264</value>
<value letter_id="G">55</value>
<value letter_id="T">-423</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">176</value>
<value letter_id="C">-429</value>
<value letter_id="G">-275</value>
<value letter_id="T">-545</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-71</value>
<value letter_id="C">-290</value>
<value letter_id="G">-388</value>
<value letter_id="T">148</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-408</value>
<value letter_id="C">202</value>
<value letter_id="G">-404</value>
<value letter_id="T">-178</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">174</value>
<value letter_id="C">-333</value>
<value letter_id="G">-278</value>
<value letter_id="T">-464</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-434</value>
<value letter_id="C">-132</value>
<value letter_id="G">-398</value>
<value letter_id="T">166</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">102</value>
<value letter_id="C">-498</value>
<value letter_id="G">88</value>
<value letter_id="T">-383</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-361</value>
<value letter_id="C">161</value>
<value letter_id="G">-319</value>
<value letter_id="T">2</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">148</value>
<value letter_id="C">-316</value>
<value letter_id="G">-34</value>
<value letter_id="T">-391</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">70</value>
<value letter_id="C">-319</value>
<value letter_id="G">120</value>
<value letter_id="T">-408</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-325</value>
<value letter_id="C">-136</value>
<value letter_id="G">-360</value>
<value letter_id="T">163</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">164</value>
<value letter_id="C">-416</value>
<value letter_id="G">-96</value>
<value letter_id="T">-671</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-587</value>
<value letter_id="C">-219</value>
<value letter_id="G">-344</value>
<value letter_id="T">172</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-225</value>
<value letter_id="C">-344</value>
<value letter_id="G">62</value>
<value letter_id="T">106</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-745</value>
<value letter_id="C">-360</value>
<value letter_id="G">-451</value>
<value letter_id="T">179</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-45</value>
<value letter_id="C">-478</value>
<value letter_id="G">177</value>
<value letter_id="T">-287</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.371795</value>
<value letter_id="C">0.020299</value>
<value letter_id="G">0.526709</value>
<value letter_id="T">0.081197</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.022970</value>
<value letter_id="C">0.014423</value>
<value letter_id="G">0.015491</value>
<value letter_id="T">0.947115</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.112179</value>
<value letter_id="C">0.000534</value>
<value letter_id="G">0.865385</value>
<value letter_id="T">0.021902</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.435363</value>
<value letter_id="C">0.018162</value>
<value letter_id="G">0.539530</value>
<value letter_id="T">0.006944</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.629274</value>
<value letter_id="C">0.035256</value>
<value letter_id="G">0.320513</value>
<value letter_id="T">0.014957</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.949786</value>
<value letter_id="C">0.011218</value>
<value letter_id="G">0.032585</value>
<value letter_id="T">0.006410</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.172009</value>
<value letter_id="C">0.029380</value>
<value letter_id="G">0.014957</value>
<value letter_id="T">0.783654</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.016560</value>
<value letter_id="C">0.888355</value>
<value letter_id="G">0.013355</value>
<value letter_id="T">0.081731</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.934829</value>
<value letter_id="C">0.021902</value>
<value letter_id="G">0.032051</value>
<value letter_id="T">0.011218</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.013889</value>
<value letter_id="C">0.088141</value>
<value letter_id="G">0.013889</value>
<value letter_id="T">0.884081</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.570513</value>
<value letter_id="C">0.006944</value>
<value letter_id="G">0.402778</value>
<value letter_id="T">0.019765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.022970</value>
<value letter_id="C">0.668803</value>
<value letter_id="G">0.024038</value>
<value letter_id="T">0.284188</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.783654</value>
<value letter_id="C">0.024573</value>
<value letter_id="G">0.173077</value>
<value letter_id="T">0.018697</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.454060</value>
<value letter_id="C">0.024038</value>
<value letter_id="G">0.505342</value>
<value letter_id="T">0.016560</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.029380</value>
<value letter_id="C">0.085470</value>
<value letter_id="G">0.018162</value>
<value letter_id="T">0.866987</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.871795</value>
<value letter_id="C">0.012286</value>
<value letter_id="G">0.113248</value>
<value letter_id="T">0.002671</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.004808</value>
<value letter_id="C">0.048077</value>
<value letter_id="G">0.020299</value>
<value letter_id="T">0.926816</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.058761</value>
<value letter_id="C">0.020299</value>
<value letter_id="G">0.338141</value>
<value letter_id="T">0.582799</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.001603</value>
<value letter_id="C">0.018162</value>
<value letter_id="G">0.009615</value>
<value letter_id="T">0.970620</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.205662</value>
<value letter_id="C">0.008013</value>
<value letter_id="G">0.747863</value>
<value letter_id="T">0.038462</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[GA]TG[GA][AG]ATCAT[AG][CT]A[GA]TAT[TG]T[GA]
</regular_expression>
<contributing_sites>
</contributing_sites>
</motif>
<motif id="motif_4" name="GCAWRTRWCAGDATTTCMTTCYTTT" alt="MEME-4" width="25" sites="1816" ic="22.6" re="21.6" llr="27150" p_value="7.5e-882" e_value="1.3e-411" bayes_threshold="9.89519" elapsed_time="758.076982">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-57</value>
<value letter_id="C">-205</value>
<value letter_id="G">167</value>
<value letter_id="T">-228</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-269</value>
<value letter_id="C">188</value>
<value letter_id="G">-247</value>
<value letter_id="T">-133</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">157</value>
<value letter_id="C">-213</value>
<value letter_id="G">-183</value>
<value letter_id="T">-238</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">43</value>
<value letter_id="C">-147</value>
<value letter_id="G">-171</value>
<value letter_id="T">76</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">77</value>
<value letter_id="C">-339</value>