<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED primary_count CDATA #REQUIRED primary_positions CDATA #REQUIRED
  control_sequences CDATA "" control_count CDATA "" control_positions CDATA "">
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_positions,
  seed,
  hsfrac,
  searchsize,
  maxsize,
  norand,
  csites,
  strands,
  brief,
  psp_file,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED
		   order CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                llr CDATA #REQUIRED
                p_value CDATA #REQUIRED
                e_value CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="5.5.5" release="Thu Sep 14 08:48:04 2023 +1000">
<training_set primary_sequences="data/tmp_memedir/10_FALSE_TRUE_FALSE_NA_15_53_113/CAMTA1.fasta" primary_count="1115" primary_positions="23415" control_sequences="--none--" control_count="0" control_positions="0">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.153</value>
<value letter_id="C">0.352</value>
<value letter_id="G">0.343</value>
<value letter_id="T">0.152</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme data/tmp_memedir/10_FALSE_TRUE_FALSE_NA_15_53_113/CAMTA1.fasta -oc data/tmp_memedir/10_FALSE_TRUE_FALSE_NA_15_53_113/CAMTA1 -nmotifs 6 -dna -maxw 15 -p 3 -seed 53 </command_line>
<host>fedora</host>
<type>zoops</type>
<nmotifs>6</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<spfun>E-value of product of p-values</spfun>
<min_width>8</min_width>
<max_width>15</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>1115</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_positions>23415</num_positions>
<seed>53</seed>
<hsfrac>0</hsfrac>
<searchsize>23415</searchsize>
<maxsize>0</maxsize>
<norand>no</norand>
<csites>1000</csites>
<strands>forward</strands>
<brief>1000</brief>
<psp_file></psp_file>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (6) found.</reason_for_stopping>
<background_frequencies source="--sequences--" order="0">
<alphabet_array>
<value letter_id="A">0.154</value>
<value letter_id="C">0.352</value>
<value letter_id="G">0.343</value>
<value letter_id="T">0.152</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="TCSATTCCATTCCAT" alt="MEME-1" width="15" sites="11" ic="22.9" re="26.6" llr="203" p_value="1.7e-063" e_value="8.2e-029" bayes_threshold="9.82426" elapsed_time="29.005747">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-75</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">258</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">121</value>
<value letter_id="G">-1010</value>
<value letter_id="T">26</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">85</value>
<value letter_id="G">9</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">257</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-191</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">24</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-191</value>
<value letter_id="T">226</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">272</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">137</value>
<value letter_id="G">-1010</value>
<value letter_id="T">-74</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-75</value>
<value letter_id="C">121</value>
<value letter_id="G">-191</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">241</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-91</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">272</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">272</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-75</value>
<value letter_id="C">121</value>
<value letter_id="G">-1010</value>
<value letter_id="T">-74</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">121</value>
<value letter_id="G">-91</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">270</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">272</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.090909</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.909091</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.818182</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.181818</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.636364</value>
<value letter_id="G">0.363636</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.909091</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.181818</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.727273</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.909091</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.090909</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.090909</value>
<value letter_id="C">0.818182</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.818182</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.181818</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.090909</value>
<value letter_id="C">0.818182</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.090909</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.818182</value>
<value letter_id="G">0.181818</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
TC[CG]ATTCCATTCCAT
</regular_expression>
<contributing_sites>
</contributing_sites>
</motif>
<motif id="motif_2" name="RCTGCRGC" alt="MEME-2" width="8" sites="77" ic="11.9" re="10.7" llr="571" p_value="5.2e-215" e_value="3.7e-019" bayes_threshold="7.86656" elapsed_time="33.282287">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">139</value>
<value letter_id="C">-1291</value>
<value letter_id="G">60</value>
<value letter_id="T">-96</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1291</value>
<value letter_id="C">150</value>
<value letter_id="G">-1291</value>
<value letter_id="T">-1291</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1291</value>
<value letter_id="C">-476</value>
<value letter_id="G">-1291</value>
<value letter_id="T">270</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1291</value>
<value letter_id="C">-1291</value>
<value letter_id="G">155</value>
<value letter_id="T">-1291</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1291</value>
<value letter_id="C">150</value>
<value letter_id="G">-1291</value>
<value letter_id="T">-1291</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">134</value>
<value letter_id="C">-1291</value>
<value letter_id="G">64</value>
<value letter_id="T">-96</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1291</value>
<value letter_id="C">-1291</value>
<value letter_id="G">155</value>
<value letter_id="T">-1291</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-56</value>
<value letter_id="C">91</value>
<value letter_id="G">-240</value>
<value letter_id="T">16</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.402597</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.519481</value>
<value letter_id="T">0.077922</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.012987</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.987013</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.389610</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.532468</value>
<value letter_id="T">0.077922</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.103896</value>
<value letter_id="C">0.662338</value>
<value letter_id="G">0.064935</value>
<value letter_id="T">0.168831</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[GA]CTGC[GA]GC
</regular_expression>
<contributing_sites>
</contributing_sites>
</motif>
<motif id="motif_3" name="RKADTARWAWDGAAW" alt="MEME-3" width="15" sites="23" ic="9.1" re="14.9" llr="237" p_value="8.6e-071" e_value="2.4e-007" bayes_threshold="9.46872" elapsed_time="37.423362">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">176</value>
<value letter_id="C">-1117</value>
<value letter_id="G">2</value>
<value letter_id="T">-22</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">50</value>
<value letter_id="C">-301</value>
<value letter_id="G">34</value>
<value letter_id="T">101</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">227</value>
<value letter_id="C">-301</value>
<value letter_id="G">-1117</value>
<value letter_id="T">52</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">118</value>
<value letter_id="C">-1117</value>
<value letter_id="G">-66</value>
<value letter_id="T">152</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-23</value>
<value letter_id="C">-1117</value>
<value letter_id="G">-66</value>
<value letter_id="T">210</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">164</value>
<value letter_id="C">-102</value>
<value letter_id="G">-98</value>
<value letter_id="T">20</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">135</value>
<value letter_id="C">-143</value>
<value letter_id="G">2</value>
<value letter_id="T">-22</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">150</value>
<value letter_id="C">-1117</value>
<value letter_id="G">-1117</value>
<value letter_id="T">190</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-70</value>
<value letter_id="G">-66</value>
<value letter_id="T">-1117</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">176</value>
<value letter_id="C">-301</value>
<value letter_id="G">-1117</value>
<value letter_id="T">152</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">50</value>
<value letter_id="C">-1117</value>
<value letter_id="G">2</value>
<value letter_id="T">152</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">76</value>
<value letter_id="C">-143</value>
<value letter_id="G">72</value>
<value letter_id="T">-180</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-1117</value>
<value letter_id="G">-98</value>
<value letter_id="T">78</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">209</value>
<value letter_id="C">-43</value>
<value letter_id="G">-297</value>
<value letter_id="T">-180</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">135</value>
<value letter_id="C">-1117</value>
<value letter_id="G">-1117</value>
<value letter_id="T">201</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.521739</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.347826</value>
<value letter_id="T">0.130435</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.217391</value>
<value letter_id="C">0.043478</value>
<value letter_id="G">0.434783</value>
<value letter_id="T">0.304348</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.739130</value>
<value letter_id="C">0.043478</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.217391</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.347826</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.217391</value>
<value letter_id="T">0.434783</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.130435</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.217391</value>
<value letter_id="T">0.652174</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.478261</value>
<value letter_id="C">0.173913</value>
<value letter_id="G">0.173913</value>
<value letter_id="T">0.173913</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.391304</value>
<value letter_id="C">0.130435</value>
<value letter_id="G">0.347826</value>
<value letter_id="T">0.130435</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.434783</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.565217</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.565217</value>
<value letter_id="C">0.217391</value>
<value letter_id="G">0.217391</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.521739</value>
<value letter_id="C">0.043478</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.434783</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.217391</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.347826</value>
<value letter_id="T">0.434783</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.260870</value>
<value letter_id="C">0.130435</value>
<value letter_id="G">0.565217</value>
<value letter_id="T">0.043478</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.565217</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.173913</value>
<value letter_id="T">0.260870</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.652174</value>
<value letter_id="C">0.260870</value>
<value letter_id="G">0.043478</value>
<value letter_id="T">0.043478</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.391304</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.608696</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[AG][GTA][AT][TAG][TG]A[AG][TA][ACG][AT][TGA][GA][AT][AC][TA]
</regular_expression>
<contributing_sites>
</contributing_sites>
</motif>
<motif id="motif_4" name="GVGGVSGGGGAGGRG" alt="MEME-4" width="15" sites="41" ic="15.5" re="12.3" llr="350" p_value="3.5e-116" e_value="2.0e-008" bayes_threshold="8.53398" elapsed_time="41.505881">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-1200</value>
<value letter_id="C">-127</value>
<value letter_id="G">128</value>
<value letter_id="T">-263</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">67</value>
<value letter_id="C">-5</value>
<value letter_id="G">28</value>
<value letter_id="T">-1200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">15</value>
<value letter_id="C">-1200</value>
<value letter_id="G">128</value>
<value letter_id="T">-1200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1200</value>
<value letter_id="C">-68</value>
<value letter_id="G">114</value>
<value letter_id="T">-263</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">52</value>
<value letter_id="C">23</value>
<value letter_id="G">-35</value>
<value letter_id="T">-64</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">15</value>
<value letter_id="C">-53</value>
<value letter_id="G">51</value>
<value letter_id="T">-64</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">67</value>
<value letter_id="C">-1200</value>
<value letter_id="G">114</value>
<value letter_id="T">-1200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">105</value>
<value letter_id="C">-1200</value>
<value letter_id="G">100</value>
<value letter_id="T">-1200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-265</value>
<value letter_id="C">-1200</value>
<value letter_id="G">147</value>
<value letter_id="T">-263</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-65</value>
<value letter_id="C">-285</value>
<value letter_id="G">132</value>
<value letter_id="T">-1200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">210</value>
<value letter_id="C">-15</value>
<value letter_id="G">-1200</value>
<value letter_id="T">-263</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1200</value>
<value letter_id="C">-385</value>
<value letter_id="G">140</value>
<value letter_id="T">-105</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-165</value>
<value letter_id="C">-1200</value>
<value letter_id="G">147</value>
<value letter_id="T">-1200</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">125</value>
<value letter_id="C">-153</value>
<value letter_id="G">0</value>
<value letter_id="T">17</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-33</value>
<value letter_id="C">-1200</value>
<value letter_id="G">136</value>
<value letter_id="T">-1200</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.146341</value>
<value letter_id="G">0.829268</value>
<value letter_id="T">0.024390</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.243902</value>
<value letter_id="C">0.341463</value>
<value letter_id="G">0.414634</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.170732</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.829268</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.219512</value>
<value letter_id="G">0.756098</value>
<value letter_id="T">0.024390</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.219512</value>
<value letter_id="C">0.414634</value>
<value letter_id="G">0.268293</value>
<value letter_id="T">0.097561</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.170732</value>
<value letter_id="C">0.243902</value>
<value letter_id="G">0.487805</value>
<value letter_id="T">0.097561</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.243902</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.756098</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.317073</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.682927</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.024390</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.951220</value>
<value letter_id="T">0.024390</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.097561</value>
<value letter_id="C">0.048780</value>
<value letter_id="G">0.853659</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.658537</value>
<value letter_id="C">0.317073</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.024390</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.024390</value>
<value letter_id="G">0.902439</value>
<value letter_id="T">0.073171</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.048780</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.951220</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.365854</value>
<value letter_id="C">0.121951</value>
<value letter_id="G">0.341463</value>
<value letter_id="T">0.170732</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.121951</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.878049</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
G[GCA]G[GC][CGA][GC][GA][GA]GG[AC]GG[AG]G
</regular_expression>
<contributing_sites>
</contributing_sites>
</motif>
<motif id="motif_5" name="WCTRCAWTKCMCAHA" alt="MEME-5" width="15" sites="8" ic="16.8" re="19.9" llr="111" p_value="5.4e-030" e_value="5.7e-001" bayes_threshold="10.6663" elapsed_time="45.497477">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">170</value>
<value letter_id="C">-965</value>
<value letter_id="G">-965</value>
<value letter_id="T">172</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-30</value>
<value letter_id="C">109</value>
<value letter_id="G">-965</value>
<value letter_id="T">-28</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-965</value>
<value letter_id="C">-965</value>
<value letter_id="G">-965</value>
<value letter_id="T">272</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">129</value>
<value letter_id="C">-965</value>
<value letter_id="G">87</value>
<value letter_id="T">-965</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-965</value>