<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Document definition -->
<!DOCTYPE MEME [
<!ELEMENT MEME (training_set , model , motifs , scanned_sites_summary?)>
<!ATTLIST MEME version CDATA #REQUIRED>
<!ATTLIST MEME release CDATA #REQUIRED>
<!-- Training-set elements --><!ELEMENT training_set (alphabet , ambigs , sequence* , letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED>
<!ATTLIST training_set primary_count CDATA #REQUIRED>
<!ATTLIST training_set primary_positions CDATA #REQUIRED>
<!ATTLIST training_set control_sequences CDATA "">
<!ATTLIST training_set control_count CDATA "">
<!ATTLIST training_set control_positions CDATA "">
<!ELEMENT alphabet (letter)*>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter)*>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED>
<!ATTLIST sequence name CDATA #REQUIRED>
<!ATTLIST sequence length CDATA #REQUIRED>
<!ATTLIST sequence weight CDATA #REQUIRED>
<!ELEMENT letter_frequencies (alphabet_array)>
<!-- Model elements --><!ELEMENT model (command_line , host , type , nmotifs , evalue_threshold , object_function , spfun , min_width , max_width , wg , ws , endgaps , minsites , maxsites , wnsites , spmap , spfuzz , prior , beta , maxiter , distance , num_positions , seed , hsfrac , searchsize , maxsize , norand , csites , strands , brief , psp_file , priors_file , reason_for_stopping , background_frequencies)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>
<!ATTLIST background_frequencies order CDATA #REQUIRED>
<!-- Motif elements --><!ELEMENT motifs (motif)*>
<!ELEMENT motif (scores , probabilities , regular_expression? , contributing_sites)>
<!ATTLIST motif id ID #REQUIRED>
<!ATTLIST motif name CDATA #REQUIRED>
<!ATTLIST motif alt CDATA "">
<!ATTLIST motif width CDATA #REQUIRED>
<!ATTLIST motif sites CDATA #REQUIRED>
<!ATTLIST motif ic CDATA #REQUIRED>
<!ATTLIST motif re CDATA #REQUIRED>
<!ATTLIST motif llr CDATA #REQUIRED>
<!ATTLIST motif p_value CDATA #REQUIRED>
<!ATTLIST motif e_value CDATA #REQUIRED>
<!ATTLIST motif bayes_threshold CDATA #REQUIRED>
<!ATTLIST motif elapsed_time CDATA #REQUIRED>
<!ATTLIST motif url CDATA "">
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>
<!-- Contributing site elements --><!-- Contributing sites are motif occurences found during the motif discovery phase --><!ELEMENT contributing_sites (contributing_site)*>
<!ELEMENT contributing_site (left_flank , site , right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED>
<!ATTLIST contributing_site position CDATA #REQUIRED>
<!ATTLIST contributing_site strand (plus | minus | none) "none">
<!ATTLIST contributing_site pvalue CDATA #REQUIRED>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start --><!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance --><!ELEMENT site (letter_ref)*>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end --><!ELEMENT right_flank (#PCDATA)>
<!-- Scanned site elements --><!-- Scanned sites are motif occurences found during the sequence scan phase --><!ELEMENT scanned_sites_summary (scanned_sites)*>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site)*>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED>
<!ATTLIST scanned_sites pvalue CDATA #REQUIRED>
<!ATTLIST scanned_sites num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site motif_id IDREF #REQUIRED>
<!ATTLIST scanned_site strand (plus | minus | none) "none">
<!ATTLIST scanned_site position CDATA #REQUIRED>
<!ATTLIST scanned_site pvalue CDATA #REQUIRED>
<!-- Utility elements --><!-- A reference to a letter in the alphabet --><!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet --><!ELEMENT alphabet_array (value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>
<!-- A alphabet_matrix contains one alphabet_array for each position in a motif --><!ELEMENT alphabet_matrix (alphabet_array)*>
]>
<!-- Begin document body -->
<MEME version="5.5.5" release="Thu Sep 14 08:48:04 2023 +1000">
  <training_set primary_sequences="data/tmp_memedir/NA_TRUE_TRUE_FALSE_50_15_53_130/ZNF407.fasta" primary_count="1165" primary_positions="140965" control_sequences="--none--" control_count="0" control_positions="0">
    <alphabet name="DNA" like="dna">
      <letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
      <letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
      <letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
      <letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
      <letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
      <letter id="V" symbol="V" equals="ACG" name="Not T"/>
      <letter id="H" symbol="H" equals="ACT" name="Not G"/>
      <letter id="D" symbol="D" equals="AGT" name="Not C"/>
      <letter id="B" symbol="B" equals="CGT" name="Not A"/>
      <letter id="M" symbol="M" equals="AC" name="Amino"/>
      <letter id="R" symbol="R" equals="AG" name="Purine"/>
      <letter id="W" symbol="W" equals="AT" name="Weak"/>
      <letter id="S" symbol="S" equals="CG" name="Strong"/>
      <letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
      <letter id="K" symbol="K" equals="GT" name="Keto"/>
    </alphabet>
    <letter_frequencies>
      <alphabet_array>
        <value letter_id="A">0.189</value>
        <value letter_id="C">0.31</value>
        <value letter_id="G">0.313</value>
        <value letter_id="T">0.189</value>
      </alphabet_array>
    </letter_frequencies>
  </training_set>
  <model>
    <command_line>meme data/tmp_memedir/NA_TRUE_TRUE_FALSE_50_15_53_130/ZNF407.fasta -oc data/tmp_memedir/NA_TRUE_TRUE_FALSE_50_15_53_130/ZNF407 -nmotifs 6 -dna -maxw 15 -p 7 -seed 53 </command_line>
    <host>ip-172-31-25-197</host>
    <type>zoops</type>
    <nmotifs>6</nmotifs>
    <evalue_threshold>inf</evalue_threshold>
    <object_function>E-value of product of p-values</object_function>
    <spfun>E-value of product of p-values</spfun>
    <min_width>8</min_width>
    <max_width>15</max_width>
    <wg>11</wg>
    <ws>1</ws>
    <endgaps>yes</endgaps>
    <substring>yes</substring>
    <minsites>2</minsites>
    <maxsites>1165</maxsites>
    <wnsites>0.8</wnsites>
    <spmap>uni</spmap>
    <spfuzz>0.5</spfuzz>
    <prior>dirichlet</prior>
    <beta>0.01</beta>
    <maxiter>50</maxiter>
    <distance>1e-05</distance>
    <num_positions>140965</num_positions>
    <seed>53</seed>
    <hsfrac>0</hsfrac>
    <searchsize>100000</searchsize>
    <maxsize>0</maxsize>
    <norand>no</norand>
    <csites>1000</csites>
    <strands>forward</strands>
    <brief>1000</brief>
    <psp_file/>
    <priors_file/>
    <reason_for_stopping>Stopped because requested number of motifs (6) found.</reason_for_stopping>
    <background_frequencies source="--sequences--" order="0">
      <alphabet_array>
        <value letter_id="A">0.189</value>
        <value letter_id="C">0.31</value>
        <value letter_id="G">0.313</value>
        <value letter_id="T">0.189</value>
      </alphabet_array>
    </background_frequencies>
  </model>
  <motifs>
    <motif id="motif_1" name="ACGGHGGCCSRSRRG" alt="MEME-1" width="15" sites="448" ic="14.7" re="13.3" llr="4122" p_value="1.8e-1222" e_value="1.1e-332" bayes_threshold="9.34039" elapsed_time="35.391408">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">239</value>
            <value letter_id="C">-1545</value>
            <value letter_id="G">-481</value>
            <value letter_id="T">-1545</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-482</value>
            <value letter_id="C">160</value>
            <value letter_id="G">-1545</value>
            <value letter_id="T">-176</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-323</value>
            <value letter_id="C">-711</value>
            <value letter_id="G">165</value>
            <value letter_id="T">-1545</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1545</value>
            <value letter_id="C">-1545</value>
            <value letter_id="G">168</value>
            <value letter_id="T">-1545</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">103</value>
            <value letter_id="C">-59</value>
            <value letter_id="G">-146</value>
            <value letter_id="T">65</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">70</value>
            <value letter_id="C">-1545</value>
            <value letter_id="G">99</value>
            <value letter_id="T">-136</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-62</value>
            <value letter_id="C">-203</value>
            <value letter_id="G">125</value>
            <value letter_id="T">-165</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1545</value>
            <value letter_id="C">150</value>
            <value letter_id="G">-135</value>
            <value letter_id="T">-640</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1545</value>
            <value letter_id="C">135</value>
            <value letter_id="G">-432</value>
            <value letter_id="T">4</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1545</value>
            <value letter_id="C">1</value>
            <value letter_id="G">85</value>
            <value letter_id="T">-59</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">107</value>
            <value letter_id="C">-116</value>
            <value letter_id="G">40</value>
            <value letter_id="T">-182</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-40</value>
            <value letter_id="C">-18</value>
            <value letter_id="G">62</value>
            <value letter_id="T">-88</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">138</value>
            <value letter_id="C">-126</value>
            <value letter_id="G">-1</value>
            <value letter_id="T">-145</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">124</value>
            <value letter_id="C">-153</value>
            <value letter_id="G">15</value>
            <value letter_id="T">-88</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-119</value>
            <value letter_id="C">-453</value>
            <value letter_id="G">148</value>
            <value letter_id="T">-249</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.988839</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.011161</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.006696</value>
            <value letter_id="C">0.937500</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.055804</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.020089</value>
            <value letter_id="C">0.002232</value>
            <value letter_id="G">0.977679</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">1.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.383929</value>
            <value letter_id="C">0.205357</value>
            <value letter_id="G">0.113839</value>
            <value letter_id="T">0.296875</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.305804</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.620536</value>
            <value letter_id="T">0.073661</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.122768</value>
            <value letter_id="C">0.075893</value>
            <value letter_id="G">0.741071</value>
            <value letter_id="T">0.060268</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.875000</value>
            <value letter_id="G">0.122768</value>
            <value letter_id="T">0.002232</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.790179</value>
            <value letter_id="G">0.015625</value>
            <value letter_id="T">0.194196</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.312500</value>
            <value letter_id="G">0.562500</value>
            <value letter_id="T">0.125000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.395089</value>
            <value letter_id="C">0.138393</value>
            <value letter_id="G">0.412946</value>
            <value letter_id="T">0.053571</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.142857</value>
            <value letter_id="C">0.274554</value>
            <value letter_id="G">0.479911</value>
            <value letter_id="T">0.102679</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.491071</value>
            <value letter_id="C">0.129464</value>
            <value letter_id="G">0.310268</value>
            <value letter_id="T">0.069196</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.444196</value>
            <value letter_id="C">0.107143</value>
            <value letter_id="G">0.345982</value>
            <value letter_id="T">0.102679</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.082589</value>
            <value letter_id="C">0.013393</value>
            <value letter_id="G">0.870536</value>
            <value letter_id="T">0.033482</value>
          </alphabet_array>
        </alphabet_matrix>
      </probabilities>
      <regular_expression>
ACGG[ATC][GA]GCC[GC][GA][GC][AG][AG]G
</regular_expression>
      <contributing_sites/>
    </motif>
    <motif id="motif_2" name="CYYSYSGGCYHCCGT" alt="MEME-2" width="15" sites="407" ic="14.8" re="13.3" llr="3743" p_value="3.3e-1130" e_value="5.9e-290" bayes_threshold="9.87511" elapsed_time="58.207220">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">-626</value>
            <value letter_id="C">151</value>
            <value letter_id="G">-299</value>
            <value letter_id="T">-136</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-113</value>
            <value letter_id="C">57</value>
            <value letter_id="G">-199</value>
            <value letter_id="T">100</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-98</value>
            <value letter_id="C">18</value>
            <value letter_id="G">-163</value>
            <value letter_id="T">126</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-168</value>
            <value letter_id="C">66</value>
            <value letter_id="G">-18</value>
            <value letter_id="T">-9</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-174</value>
            <value letter_id="C">50</value>
            <value letter_id="G">-116</value>
            <value letter_id="T">96</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-74</value>
            <value letter_id="C">79</value>
            <value letter_id="G">11</value>
            <value letter_id="T">-368</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-18</value>
            <value letter_id="C">-1531</value>
            <value letter_id="G">141</value>
            <value letter_id="T">-1531</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-468</value>
            <value letter_id="C">-112</value>
            <value letter_id="G">144</value>
            <value letter_id="T">-1531</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-209</value>
            <value letter_id="C">136</value>
            <value letter_id="G">-267</value>
            <value letter_id="T">-77</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-168</value>
            <value letter_id="C">78</value>
            <value letter_id="G">-540</value>
            <value letter_id="T">109</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">48</value>
            <value letter_id="C">-64</value>
            <value letter_id="G">-95</value>
            <value letter_id="T">100</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1531</value>
            <value letter_id="C">169</value>
            <value letter_id="G">-1531</value>
            <value letter_id="T">-1531</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1531</value>
            <value letter_id="C">167</value>
            <value letter_id="G">-599</value>
            <value letter_id="T">-426</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-140</value>
            <value letter_id="C">-417</value>
            <value letter_id="G">154</value>
            <value letter_id="T">-1531</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1531</value>
            <value letter_id="C">-698</value>
            <value letter_id="G">-418</value>
            <value letter_id="T">238</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.002457</value>
            <value letter_id="C">0.884521</value>
            <value letter_id="G">0.039312</value>
            <value letter_id="T">0.073710</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.085995</value>
            <value letter_id="C">0.459459</value>
            <value letter_id="G">0.078624</value>
            <value letter_id="T">0.375921</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.095823</value>
            <value letter_id="C">0.351351</value>
            <value letter_id="G">0.100737</value>
            <value letter_id="T">0.452088</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.058968</value>
            <value letter_id="C">0.488943</value>
            <value letter_id="G">0.275184</value>
            <value letter_id="T">0.176904</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.056511</value>
            <value letter_id="C">0.437346</value>
            <value letter_id="G">0.140049</value>
            <value letter_id="T">0.366093</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.113022</value>
            <value letter_id="C">0.535627</value>
            <value letter_id="G">0.336609</value>
            <value letter_id="T">0.014742</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.167076</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.832924</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.007371</value>
            <value letter_id="C">0.142506</value>
            <value letter_id="G">0.850123</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.044226</value>
            <value letter_id="C">0.796069</value>
            <value letter_id="G">0.049140</value>
            <value letter_id="T">0.110565</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.058968</value>
            <value letter_id="C">0.533170</value>
            <value letter_id="G">0.007371</value>
            <value letter_id="T">0.400491</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.262899</value>
            <value letter_id="C">0.199017</value>
            <value letter_id="G">0.162162</value>
            <value letter_id="T">0.375921</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">1.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.985258</value>
            <value letter_id="G">0.004914</value>
            <value letter_id="T">0.009828</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.071253</value>
            <value letter_id="C">0.017199</value>
            <value letter_id="G">0.911548</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.002457</value>
            <value letter_id="G">0.017199</value>
            <value letter_id="T">0.980344</value>
          </alphabet_array>
        </alphabet_matrix>
      </probabilities>
      <regular_expression>
C[CT][TC][CG][CT][CG]GGC[CT][TA]CCGT
</regular_expression>
      <contributing_sites/>
    </motif>
    <motif id="motif_3" name="AARAWRVAARAMDWA" alt="MEME-3" width="15" sites="83" ic="12.7" re="15.8" llr="911" p_value="5.1e-282" e_value="1.7e-052" bayes_threshold="12.4038" elapsed_time="80.227096">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">208</value>
            <value letter_id="C">-169</value>
            <value letter_id="G">-1302</value>
            <value letter_id="T">-80</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">194</value>
            <value letter_id="C">-310</value>
            <value letter_id="G">-38</value>
            <value letter_id="T">-1302</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">159</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">47</value>
            <value letter_id="T">-1302</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">196</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">-24</value>
            <value letter_id="T">-1302</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">149</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">-124</value>
            <value letter_id="T">84</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">149</value>
            <value letter_id="C">-269</value>
            <value letter_id="G">43</value>
            <value letter_id="T">-1302</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">103</value>
            <value letter_id="C">-4</value>
            <value letter_id="G">0</value>
            <value letter_id="T">-1302</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">220</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">-1302</value>
            <value letter_id="T">-51</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">235</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">-311</value>
            <value letter_id="T">-1302</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">168</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">0</value>
            <value letter_id="T">-116</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">165</value>
            <value letter_id="C">-136</value>
            <value letter_id="G">-11</value>
            <value letter_id="T">-1302</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">142</value>
            <value letter_id="C">-10</value>
            <value letter_id="G">-189</value>
            <value letter_id="T">-65</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">20</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">26</value>
            <value letter_id="T">112</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">103</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">-170</value>
            <value letter_id="T">146</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">162</value>
            <value letter_id="C">-1302</value>
            <value letter_id="G">-89</value>
            <value letter_id="T">42</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.795181</value>
            <value letter_id="C">0.096386</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.108434</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.722892</value>
            <value letter_id="C">0.036145</value>
            <value letter_id="G">0.240964</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.566265</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.433735</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.734940</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.265060</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.530120</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.132530</value>
            <value letter_id="T">0.337349</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.530120</value>
            <value letter_id="C">0.048193</value>
            <value letter_id="G">0.421687</value>
            <value letter_id="T">0.000000</value>