<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Document definition -->
<!DOCTYPE MEME [
<!ELEMENT MEME (training_set , model , motifs , scanned_sites_summary?)>
<!ATTLIST MEME version CDATA #REQUIRED>
<!ATTLIST MEME release CDATA #REQUIRED>
<!-- Training-set elements --><!ELEMENT training_set (alphabet , ambigs , sequence* , letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED>
<!ATTLIST training_set primary_count CDATA #REQUIRED>
<!ATTLIST training_set primary_positions CDATA #REQUIRED>
<!ATTLIST training_set control_sequences CDATA "">
<!ATTLIST training_set control_count CDATA "">
<!ATTLIST training_set control_positions CDATA "">
<!ELEMENT alphabet (letter)*>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter)*>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED>
<!ATTLIST sequence name CDATA #REQUIRED>
<!ATTLIST sequence length CDATA #REQUIRED>
<!ATTLIST sequence weight CDATA #REQUIRED>
<!ELEMENT letter_frequencies (alphabet_array)>
<!-- Model elements --><!ELEMENT model (command_line , host , type , nmotifs , evalue_threshold , object_function , spfun , min_width , max_width , wg , ws , endgaps , minsites , maxsites , wnsites , spmap , spfuzz , prior , beta , maxiter , distance , num_positions , seed , hsfrac , searchsize , maxsize , norand , csites , strands , brief , psp_file , priors_file , reason_for_stopping , background_frequencies)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>
<!ATTLIST background_frequencies order CDATA #REQUIRED>
<!-- Motif elements --><!ELEMENT motifs (motif)*>
<!ELEMENT motif (scores , probabilities , regular_expression? , contributing_sites)>
<!ATTLIST motif id ID #REQUIRED>
<!ATTLIST motif name CDATA #REQUIRED>
<!ATTLIST motif alt CDATA "">
<!ATTLIST motif width CDATA #REQUIRED>
<!ATTLIST motif sites CDATA #REQUIRED>
<!ATTLIST motif ic CDATA #REQUIRED>
<!ATTLIST motif re CDATA #REQUIRED>
<!ATTLIST motif llr CDATA #REQUIRED>
<!ATTLIST motif p_value CDATA #REQUIRED>
<!ATTLIST motif e_value CDATA #REQUIRED>
<!ATTLIST motif bayes_threshold CDATA #REQUIRED>
<!ATTLIST motif elapsed_time CDATA #REQUIRED>
<!ATTLIST motif url CDATA "">
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>
<!-- Contributing site elements --><!-- Contributing sites are motif occurences found during the motif discovery phase --><!ELEMENT contributing_sites (contributing_site)*>
<!ELEMENT contributing_site (left_flank , site , right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED>
<!ATTLIST contributing_site position CDATA #REQUIRED>
<!ATTLIST contributing_site strand (plus | minus | none) "none">
<!ATTLIST contributing_site pvalue CDATA #REQUIRED>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start --><!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance --><!ELEMENT site (letter_ref)*>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end --><!ELEMENT right_flank (#PCDATA)>
<!-- Scanned site elements --><!-- Scanned sites are motif occurences found during the sequence scan phase --><!ELEMENT scanned_sites_summary (scanned_sites)*>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site)*>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED>
<!ATTLIST scanned_sites pvalue CDATA #REQUIRED>
<!ATTLIST scanned_sites num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site motif_id IDREF #REQUIRED>
<!ATTLIST scanned_site strand (plus | minus | none) "none">
<!ATTLIST scanned_site position CDATA #REQUIRED>
<!ATTLIST scanned_site pvalue CDATA #REQUIRED>
<!-- Utility elements --><!-- A reference to a letter in the alphabet --><!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet --><!ELEMENT alphabet_array (value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>
<!-- A alphabet_matrix contains one alphabet_array for each position in a motif --><!ELEMENT alphabet_matrix (alphabet_array)*>
]>
<!-- Begin document body -->
<MEME version="5.5.5" release="Thu Sep 14 08:48:04 2023 +1000">
  <training_set primary_sequences="data/tmp_memedir/10_TRUE_FALSE_TRUE_75_15_53_43/ZNF407.fasta" primary_count="306" primary_positions="6426" control_sequences="--none--" control_count="0" control_positions="0">
    <alphabet name="DNA" like="dna">
      <letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
      <letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
      <letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
      <letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
      <letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
      <letter id="V" symbol="V" equals="ACG" name="Not T"/>
      <letter id="H" symbol="H" equals="ACT" name="Not G"/>
      <letter id="D" symbol="D" equals="AGT" name="Not C"/>
      <letter id="B" symbol="B" equals="CGT" name="Not A"/>
      <letter id="M" symbol="M" equals="AC" name="Amino"/>
      <letter id="R" symbol="R" equals="AG" name="Purine"/>
      <letter id="W" symbol="W" equals="AT" name="Weak"/>
      <letter id="S" symbol="S" equals="CG" name="Strong"/>
      <letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
      <letter id="K" symbol="K" equals="GT" name="Keto"/>
    </alphabet>
    <sequence id="sequence_0" name="3264" length="21" weight="1.000000"/>
    <sequence id="sequence_1" name="3265" length="21" weight="1.000000"/>
    <sequence id="sequence_2" name="3266" length="21" weight="1.000000"/>
    <sequence id="sequence_3" name="3267" length="21" weight="1.000000"/>
    <sequence id="sequence_4" name="3268" length="21" weight="1.000000"/>
    <sequence id="sequence_5" name="3269" length="21" weight="1.000000"/>
    <sequence id="sequence_6" name="3270" length="21" weight="1.000000"/>
    <sequence id="sequence_7" name="3271" length="21" weight="1.000000"/>
    <sequence id="sequence_8" name="3272" length="21" weight="1.000000"/>
    <sequence id="sequence_9" name="3273" length="21" weight="1.000000"/>
    <sequence id="sequence_10" name="3274" length="21" weight="1.000000"/>
    <sequence id="sequence_11" name="3275" length="21" weight="1.000000"/>
    <sequence id="sequence_12" name="3276" length="21" weight="1.000000"/>
    <sequence id="sequence_13" name="3277" length="21" weight="1.000000"/>
    <sequence id="sequence_14" name="3278" length="21" weight="1.000000"/>
    <sequence id="sequence_15" name="3279" length="21" weight="1.000000"/>
    <sequence id="sequence_16" name="3280" length="21" weight="1.000000"/>
    <sequence id="sequence_17" name="3281" length="21" weight="1.000000"/>
    <sequence id="sequence_18" name="3282" length="21" weight="1.000000"/>
    <sequence id="sequence_19" name="3283" length="21" weight="1.000000"/>
    <sequence id="sequence_20" name="3284" length="21" weight="1.000000"/>
    <sequence id="sequence_21" name="3285" length="21" weight="1.000000"/>
    <sequence id="sequence_22" name="3286" length="21" weight="1.000000"/>
    <sequence id="sequence_23" name="3287" length="21" weight="1.000000"/>
    <sequence id="sequence_24" name="3288" length="21" weight="1.000000"/>
    <sequence id="sequence_25" name="3289" length="21" weight="1.000000"/>
    <sequence id="sequence_26" name="3290" length="21" weight="1.000000"/>
    <sequence id="sequence_27" name="3291" length="21" weight="1.000000"/>
    <sequence id="sequence_28" name="3292" length="21" weight="1.000000"/>
    <sequence id="sequence_29" name="3293" length="21" weight="1.000000"/>
    <sequence id="sequence_30" name="3294" length="21" weight="1.000000"/>
    <sequence id="sequence_31" name="3295" length="21" weight="1.000000"/>
    <sequence id="sequence_32" name="3296" length="21" weight="1.000000"/>
    <sequence id="sequence_33" name="3297" length="21" weight="1.000000"/>
    <sequence id="sequence_34" name="3298" length="21" weight="1.000000"/>
    <sequence id="sequence_35" name="3299" length="21" weight="1.000000"/>
    <sequence id="sequence_36" name="3300" length="21" weight="1.000000"/>
    <sequence id="sequence_37" name="3301" length="21" weight="1.000000"/>
    <sequence id="sequence_38" name="3302" length="21" weight="1.000000"/>
    <sequence id="sequence_39" name="3303" length="21" weight="1.000000"/>
    <sequence id="sequence_40" name="3304" length="21" weight="1.000000"/>
    <sequence id="sequence_41" name="3305" length="21" weight="1.000000"/>
    <sequence id="sequence_42" name="3306" length="21" weight="1.000000"/>
    <sequence id="sequence_43" name="3307" length="21" weight="1.000000"/>
    <sequence id="sequence_44" name="3308" length="21" weight="1.000000"/>
    <sequence id="sequence_45" name="3309" length="21" weight="1.000000"/>
    <sequence id="sequence_46" name="3310" length="21" weight="1.000000"/>
    <sequence id="sequence_47" name="3311" length="21" weight="1.000000"/>
    <sequence id="sequence_48" name="3312" length="21" weight="1.000000"/>
    <sequence id="sequence_49" name="3313" length="21" weight="1.000000"/>
    <sequence id="sequence_50" name="3314" length="21" weight="1.000000"/>
    <sequence id="sequence_51" name="3315" length="21" weight="1.000000"/>
    <sequence id="sequence_52" name="3316" length="21" weight="1.000000"/>
    <sequence id="sequence_53" name="3317" length="21" weight="1.000000"/>
    <sequence id="sequence_54" name="3318" length="21" weight="1.000000"/>
    <sequence id="sequence_55" name="3319" length="21" weight="1.000000"/>
    <sequence id="sequence_56" name="3320" length="21" weight="1.000000"/>
    <sequence id="sequence_57" name="3321" length="21" weight="1.000000"/>
    <sequence id="sequence_58" name="3322" length="21" weight="1.000000"/>
    <sequence id="sequence_59" name="3323" length="21" weight="1.000000"/>
    <sequence id="sequence_60" name="3324" length="21" weight="1.000000"/>
    <sequence id="sequence_61" name="3325" length="21" weight="1.000000"/>
    <sequence id="sequence_62" name="3326" length="21" weight="1.000000"/>
    <sequence id="sequence_63" name="3327" length="21" weight="1.000000"/>
    <sequence id="sequence_64" name="3328" length="21" weight="1.000000"/>
    <sequence id="sequence_65" name="3329" length="21" weight="1.000000"/>
    <sequence id="sequence_66" name="3330" length="21" weight="1.000000"/>
    <sequence id="sequence_67" name="3331" length="21" weight="1.000000"/>
    <sequence id="sequence_68" name="3332" length="21" weight="1.000000"/>
    <sequence id="sequence_69" name="3333" length="21" weight="1.000000"/>
    <sequence id="sequence_70" name="3334" length="21" weight="1.000000"/>
    <sequence id="sequence_71" name="3335" length="21" weight="1.000000"/>
    <sequence id="sequence_72" name="3336" length="21" weight="1.000000"/>
    <sequence id="sequence_73" name="3337" length="21" weight="1.000000"/>
    <sequence id="sequence_74" name="3338" length="21" weight="1.000000"/>
    <sequence id="sequence_75" name="3339" length="21" weight="1.000000"/>
    <sequence id="sequence_76" name="3340" length="21" weight="1.000000"/>
    <sequence id="sequence_77" name="3341" length="21" weight="1.000000"/>
    <sequence id="sequence_78" name="3342" length="21" weight="1.000000"/>
    <sequence id="sequence_79" name="3343" length="21" weight="1.000000"/>
    <sequence id="sequence_80" name="3344" length="21" weight="1.000000"/>
    <sequence id="sequence_81" name="3345" length="21" weight="1.000000"/>
    <sequence id="sequence_82" name="3346" length="21" weight="1.000000"/>
    <sequence id="sequence_83" name="3347" length="21" weight="1.000000"/>
    <sequence id="sequence_84" name="3348" length="21" weight="1.000000"/>
    <sequence id="sequence_85" name="3349" length="21" weight="1.000000"/>
    <sequence id="sequence_86" name="3350" length="21" weight="1.000000"/>
    <sequence id="sequence_87" name="3351" length="21" weight="1.000000"/>
    <sequence id="sequence_88" name="3352" length="21" weight="1.000000"/>
    <sequence id="sequence_89" name="3353" length="21" weight="1.000000"/>
    <sequence id="sequence_90" name="3354" length="21" weight="1.000000"/>
    <sequence id="sequence_91" name="3355" length="21" weight="1.000000"/>
    <sequence id="sequence_92" name="3356" length="21" weight="1.000000"/>
    <sequence id="sequence_93" name="3357" length="21" weight="1.000000"/>
    <sequence id="sequence_94" name="3358" length="21" weight="1.000000"/>
    <sequence id="sequence_95" name="3359" length="21" weight="1.000000"/>
    <sequence id="sequence_96" name="3360" length="21" weight="1.000000"/>
    <sequence id="sequence_97" name="3361" length="21" weight="1.000000"/>
    <sequence id="sequence_98" name="3362" length="21" weight="1.000000"/>
    <sequence id="sequence_99" name="3363" length="21" weight="1.000000"/>
    <sequence id="sequence_100" name="3364" length="21" weight="1.000000"/>
    <sequence id="sequence_101" name="3365" length="21" weight="1.000000"/>
    <sequence id="sequence_102" name="3366" length="21" weight="1.000000"/>
    <sequence id="sequence_103" name="3367" length="21" weight="1.000000"/>
    <sequence id="sequence_104" name="3368" length="21" weight="1.000000"/>
    <sequence id="sequence_105" name="3369" length="21" weight="1.000000"/>
    <sequence id="sequence_106" name="3370" length="21" weight="1.000000"/>
    <sequence id="sequence_107" name="3371" length="21" weight="1.000000"/>
    <sequence id="sequence_108" name="3372" length="21" weight="1.000000"/>
    <sequence id="sequence_109" name="3373" length="21" weight="1.000000"/>
    <sequence id="sequence_110" name="3374" length="21" weight="1.000000"/>
    <sequence id="sequence_111" name="3375" length="21" weight="1.000000"/>
    <sequence id="sequence_112" name="3376" length="21" weight="1.000000"/>
    <sequence id="sequence_113" name="3377" length="21" weight="1.000000"/>
    <sequence id="sequence_114" name="3378" length="21" weight="1.000000"/>
    <sequence id="sequence_115" name="3379" length="21" weight="1.000000"/>
    <sequence id="sequence_116" name="3380" length="21" weight="1.000000"/>
    <sequence id="sequence_117" name="3381" length="21" weight="1.000000"/>
    <sequence id="sequence_118" name="3382" length="21" weight="1.000000"/>
    <sequence id="sequence_119" name="3383" length="21" weight="1.000000"/>
    <sequence id="sequence_120" name="3384" length="21" weight="1.000000"/>
    <sequence id="sequence_121" name="3385" length="21" weight="1.000000"/>
    <sequence id="sequence_122" name="3386" length="21" weight="1.000000"/>
    <sequence id="sequence_123" name="3387" length="21" weight="1.000000"/>
    <sequence id="sequence_124" name="3388" length="21" weight="1.000000"/>
    <sequence id="sequence_125" name="3389" length="21" weight="1.000000"/>
    <sequence id="sequence_126" name="3390" length="21" weight="1.000000"/>
    <sequence id="sequence_127" name="3391" length="21" weight="1.000000"/>
    <sequence id="sequence_128" name="3392" length="21" weight="1.000000"/>
    <sequence id="sequence_129" name="3393" length="21" weight="1.000000"/>
    <sequence id="sequence_130" name="3394" length="21" weight="1.000000"/>
    <sequence id="sequence_131" name="3395" length="21" weight="1.000000"/>
    <sequence id="sequence_132" name="3396" length="21" weight="1.000000"/>
    <sequence id="sequence_133" name="3397" length="21" weight="1.000000"/>
    <sequence id="sequence_134" name="3398" length="21" weight="1.000000"/>
    <sequence id="sequence_135" name="3399" length="21" weight="1.000000"/>
    <sequence id="sequence_136" name="3400" length="21" weight="1.000000"/>
    <sequence id="sequence_137" name="3401" length="21" weight="1.000000"/>
    <sequence id="sequence_138" name="3402" length="21" weight="1.000000"/>
    <sequence id="sequence_139" name="3403" length="21" weight="1.000000"/>
    <sequence id="sequence_140" name="3404" length="21" weight="1.000000"/>
    <sequence id="sequence_141" name="3405" length="21" weight="1.000000"/>
    <sequence id="sequence_142" name="3406" length="21" weight="1.000000"/>
    <sequence id="sequence_143" name="3407" length="21" weight="1.000000"/>
    <sequence id="sequence_144" name="3408" length="21" weight="1.000000"/>
    <sequence id="sequence_145" name="3409" length="21" weight="1.000000"/>
    <sequence id="sequence_146" name="3410" length="21" weight="1.000000"/>
    <sequence id="sequence_147" name="3411" length="21" weight="1.000000"/>
    <sequence id="sequence_148" name="3412" length="21" weight="1.000000"/>
    <sequence id="sequence_149" name="3413" length="21" weight="1.000000"/>
    <sequence id="sequence_150" name="3414" length="21" weight="1.000000"/>
    <sequence id="sequence_151" name="3415" length="21" weight="1.000000"/>
    <sequence id="sequence_152" name="3416" length="21" weight="1.000000"/>
    <sequence id="sequence_153" name="3417" length="21" weight="1.000000"/>
    <sequence id="sequence_154" name="3418" length="21" weight="1.000000"/>
    <sequence id="sequence_155" name="3419" length="21" weight="1.000000"/>
    <sequence id="sequence_156" name="3420" length="21" weight="1.000000"/>
    <sequence id="sequence_157" name="3421" length="21" weight="1.000000"/>
    <sequence id="sequence_158" name="3422" length="21" weight="1.000000"/>
    <sequence id="sequence_159" name="3423" length="21" weight="1.000000"/>
    <sequence id="sequence_160" name="3424" length="21" weight="1.000000"/>
    <sequence id="sequence_161" name="3425" length="21" weight="1.000000"/>
    <sequence id="sequence_162" name="3426" length="21" weight="1.000000"/>
    <sequence id="sequence_163" name="3427" length="21" weight="1.000000"/>
    <sequence id="sequence_164" name="3428" length="21" weight="1.000000"/>
    <sequence id="sequence_165" name="3429" length="21" weight="1.000000"/>
    <sequence id="sequence_166" name="3430" length="21" weight="1.000000"/>
    <sequence id="sequence_167" name="3431" length="21" weight="1.000000"/>
    <sequence id="sequence_168" name="3432" length="21" weight="1.000000"/>
    <sequence id="sequence_169" name="3433" length="21" weight="1.000000"/>
    <sequence id="sequence_170" name="3434" length="21" weight="1.000000"/>
    <sequence id="sequence_171" name="3435" length="21" weight="1.000000"/>
    <sequence id="sequence_172" name="3436" length="21" weight="1.000000"/>
    <sequence id="sequence_173" name="3437" length="21" weight="1.000000"/>
    <sequence id="sequence_174" name="3438" length="21" weight="1.000000"/>
    <sequence id="sequence_175" name="3439" length="21" weight="1.000000"/>
    <sequence id="sequence_176" name="3440" length="21" weight="1.000000"/>
    <sequence id="sequence_177" name="3441" length="21" weight="1.000000"/>
    <sequence id="sequence_178" name="3442" length="21" weight="1.000000"/>
    <sequence id="sequence_179" name="3443" length="21" weight="1.000000"/>
    <sequence id="sequence_180" name="3444" length="21" weight="1.000000"/>
    <sequence id="sequence_181" name="3445" length="21" weight="1.000000"/>
    <sequence id="sequence_182" name="3446" length="21" weight="1.000000"/>
    <sequence id="sequence_183" name="3447" length="21" weight="1.000000"/>
    <sequence id="sequence_184" name="3448" length="21" weight="1.000000"/>
    <sequence id="sequence_185" name="3449" length="21" weight="1.000000"/>
    <sequence id="sequence_186" name="3450" length="21" weight="1.000000"/>
    <sequence id="sequence_187" name="3451" length="21" weight="1.000000"/>
    <sequence id="sequence_188" name="3452" length="21" weight="1.000000"/>
    <sequence id="sequence_189" name="3453" length="21" weight="1.000000"/>
    <sequence id="sequence_190" name="3454" length="21" weight="1.000000"/>
    <sequence id="sequence_191" name="3455" length="21" weight="1.000000"/>
    <sequence id="sequence_192" name="3456" length="21" weight="1.000000"/>
    <sequence id="sequence_193" name="3457" length="21" weight="1.000000"/>
    <sequence id="sequence_194" name="3458" length="21" weight="1.000000"/>
    <sequence id="sequence_195" name="3459" length="21" weight="1.000000"/>
    <sequence id="sequence_196" name="3460" length="21" weight="1.000000"/>
    <sequence id="sequence_197" name="3461" length="21" weight="1.000000"/>
    <sequence id="sequence_198" name="3462" length="21" weight="1.000000"/>
    <sequence id="sequence_199" name="3463" length="21" weight="1.000000"/>
    <sequence id="sequence_200" name="3464" length="21" weight="1.000000"/>
    <sequence id="sequence_201" name="3465" length="21" weight="1.000000"/>
    <sequence id="sequence_202" name="3466" length="21" weight="1.000000"/>
    <sequence id="sequence_203" name="3467" length="21" weight="1.000000"/>
    <sequence id="sequence_204" name="3468" length="21" weight="1.000000"/>
    <sequence id="sequence_205" name="3469" length="21" weight="1.000000"/>
    <sequence id="sequence_206" name="3470" length="21" weight="1.000000"/>
    <sequence id="sequence_207" name="3471" length="21" weight="1.000000"/>
    <sequence id="sequence_208" name="3472" length="21" weight="1.000000"/>
    <sequence id="sequence_209" name="3473" length="21" weight="1.000000"/>
    <sequence id="sequence_210" name="3474" length="21" weight="1.000000"/>
    <sequence id="sequence_211" name="3475" length="21" weight="1.000000"/>
    <sequence id="sequence_212" name="3476" length="21" weight="1.000000"/>
    <sequence id="sequence_213" name="3477" length="21" weight="1.000000"/>
    <sequence id="sequence_214" name="3478" length="21" weight="1.000000"/>
    <sequence id="sequence_215" name="3479" length="21" weight="1.000000"/>
    <sequence id="sequence_216" name="3480" length="21" weight="1.000000"/>
    <sequence id="sequence_217" name="3481" length="21" weight="1.000000"/>
    <sequence id="sequence_218" name="3482" length="21" weight="1.000000"/>
    <sequence id="sequence_219" name="3483" length="21" weight="1.000000"/>
    <sequence id="sequence_220" name="3484" length="21" weight="1.000000"/>
    <sequence id="sequence_221" name="3485" length="21" weight="1.000000"/>
    <sequence id="sequence_222" name="3486" length="21" weight="1.000000"/>
    <sequence id="sequence_223" name="3487" length="21" weight="1.000000"/>
    <sequence id="sequence_224" name="3488" length="21" weight="1.000000"/>
    <sequence id="sequence_225" name="3489" length="21" weight="1.000000"/>
    <sequence id="sequence_226" name="3490" length="21" weight="1.000000"/>
    <sequence id="sequence_227" name="3491" length="21" weight="1.000000"/>
    <sequence id="sequence_228" name="3492" length="21" weight="1.000000"/>
    <sequence id="sequence_229" name="3493" length="21" weight="1.000000"/>
    <sequence id="sequence_230" name="3494" length="21" weight="1.000000"/>
    <sequence id="sequence_231" name="3495" length="21" weight="1.000000"/>
    <sequence id="sequence_232" name="3496" length="21" weight="1.000000"/>
    <sequence id="sequence_233" name="3497" length="21" weight="1.000000"/>
    <sequence id="sequence_234" name="3498" length="21" weight="1.000000"/>
    <sequence id="sequence_235" name="3499" length="21" weight="1.000000"/>
    <sequence id="sequence_236" name="3500" length="21" weight="1.000000"/>
    <sequence id="sequence_237" name="3501" length="21" weight="1.000000"/>
    <sequence id="sequence_238" name="3502" length="21" weight="1.000000"/>
    <sequence id="sequence_239" name="3503" length="21" weight="1.000000"/>
    <sequence id="sequence_240" name="3504" length="21" weight="1.000000"/>
    <sequence id="sequence_241" name="3505" length="21" weight="1.000000"/>
    <sequence id="sequence_242" name="3506" length="21" weight="1.000000"/>
    <sequence id="sequence_243" name="3507" length="21" weight="1.000000"/>
    <sequence id="sequence_244" name="3508" length="21" weight="1.000000"/>
    <sequence id="sequence_245" name="3509" length="21" weight="1.000000"/>
    <sequence id="sequence_246" name="3510" length="21" weight="1.000000"/>
    <sequence id="sequence_247" name="3511" length="21" weight="1.000000"/>
    <sequence id="sequence_248" name="3512" length="21" weight="1.000000"/>
    <sequence id="sequence_249" name="3513" length="21" weight="1.000000"/>
    <sequence id="sequence_250" name="3514" length="21" weight="1.000000"/>
    <sequence id="sequence_251" name="3515" length="21" weight="1.000000"/>
    <sequence id="sequence_252" name="3516" length="21" weight="1.000000"/>
    <sequence id="sequence_253" name="3517" length="21" weight="1.000000"/>
    <sequence id="sequence_254" name="3518" length="21" weight="1.000000"/>
    <sequence id="sequence_255" name="3519" length="21" weight="1.000000"/>
    <sequence id="sequence_256" name="3520" length="21" weight="1.000000"/>
    <sequence id="sequence_257" name="3521" length="21" weight="1.000000"/>
    <sequence id="sequence_258" name="3522" length="21" weight="1.000000"/>
    <sequence id="sequence_259" name="3523" length="21" weight="1.000000"/>
    <sequence id="sequence_260" name="3524" length="21" weight="1.000000"/>
    <sequence id="sequence_261" name="3525" length="21" weight="1.000000"/>
    <sequence id="sequence_262" name="3526" length="21" weight="1.000000"/>
    <sequence id="sequence_263" name="3527" length="21" weight="1.000000"/>
    <sequence id="sequence_264" name="3528" length="21" weight="1.000000"/>
    <sequence id="sequence_265" name="3529" length="21" weight="1.000000"/>
    <sequence id="sequence_266" name="3530" length="21" weight="1.000000"/>
    <sequence id="sequence_267" name="3531" length="21" weight="1.000000"/>
    <sequence id="sequence_268" name="3532" length="21" weight="1.000000"/>
    <sequence id="sequence_269" name="3533" length="21" weight="1.000000"/>
    <sequence id="sequence_270" name="3534" length="21" weight="1.000000"/>
    <sequence id="sequence_271" name="3535" length="21" weight="1.000000"/>
    <sequence id="sequence_272" name="3536" length="21" weight="1.000000"/>
    <sequence id="sequence_273" name="3537" length="21" weight="1.000000"/>
    <sequence id="sequence_274" name="3538" length="21" weight="1.000000"/>
    <sequence id="sequence_275" name="3539" length="21" weight="1.000000"/>
    <sequence id="sequence_276" name="3540" length="21" weight="1.000000"/>
    <sequence id="sequence_277" name="3541" length="21" weight="1.000000"/>
    <sequence id="sequence_278" name="3542" length="21" weight="1.000000"/>
    <sequence id="sequence_279" name="3543" length="21" weight="1.000000"/>
    <sequence id="sequence_280" name="3544" length="21" weight="1.000000"/>
    <sequence id="sequence_281" name="3545" length="21" weight="1.000000"/>
    <sequence id="sequence_282" name="3546" length="21" weight="1.000000"/>
    <sequence id="sequence_283" name="3547" length="21" weight="1.000000"/>
    <sequence id="sequence_284" name="3548" length="21" weight="1.000000"/>
    <sequence id="sequence_285" name="3549" length="21" weight="1.000000"/>
    <sequence id="sequence_286" name="3550" length="21" weight="1.000000"/>
    <sequence id="sequence_287" name="3551" length="21" weight="1.000000"/>
    <sequence id="sequence_288" name="3552" length="21" weight="1.000000"/>
    <sequence id="sequence_289" name="3553" length="21" weight="1.000000"/>
    <sequence id="sequence_290" name="3554" length="21" weight="1.000000"/>
    <sequence id="sequence_291" name="3555" length="21" weight="1.000000"/>
    <sequence id="sequence_292" name="3556" length="21" weight="1.000000"/>
    <sequence id="sequence_293" name="3557" length="21" weight="1.000000"/>
    <sequence id="sequence_294" name="3558" length="21" weight="1.000000"/>
    <sequence id="sequence_295" name="3559" length="21" weight="1.000000"/>
    <sequence id="sequence_296" name="3560" length="21" weight="1.000000"/>
    <sequence id="sequence_297" name="3561" length="21" weight="1.000000"/>
    <sequence id="sequence_298" name="3562" length="21" weight="1.000000"/>
    <sequence id="sequence_299" name="3563" length="21" weight="1.000000"/>
    <sequence id="sequence_300" name="3564" length="21" weight="1.000000"/>
    <sequence id="sequence_301" name="3565" length="21" weight="1.000000"/>
    <sequence id="sequence_302" name="3566" length="21" weight="1.000000"/>
    <sequence id="sequence_303" name="3567" length="21" weight="1.000000"/>