<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Document definition -->
<!DOCTYPE MEME [
<!ELEMENT MEME (training_set , model , motifs , scanned_sites_summary?)>
<!ATTLIST MEME version CDATA #REQUIRED>
<!ATTLIST MEME release CDATA #REQUIRED>
<!-- Training-set elements --><!ELEMENT training_set (alphabet , ambigs , sequence* , letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED>
<!ATTLIST training_set primary_count CDATA #REQUIRED>
<!ATTLIST training_set primary_positions CDATA #REQUIRED>
<!ATTLIST training_set control_sequences CDATA "">
<!ATTLIST training_set control_count CDATA "">
<!ATTLIST training_set control_positions CDATA "">
<!ELEMENT alphabet (letter)*>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter)*>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED>
<!ATTLIST sequence name CDATA #REQUIRED>
<!ATTLIST sequence length CDATA #REQUIRED>
<!ATTLIST sequence weight CDATA #REQUIRED>
<!ELEMENT letter_frequencies (alphabet_array)>
<!-- Model elements --><!ELEMENT model (command_line , host , type , nmotifs , evalue_threshold , object_function , spfun , min_width , max_width , wg , ws , endgaps , minsites , maxsites , wnsites , spmap , spfuzz , prior , beta , maxiter , distance , num_positions , seed , hsfrac , searchsize , maxsize , norand , csites , strands , brief , psp_file , priors_file , reason_for_stopping , background_frequencies)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>
<!ATTLIST background_frequencies order CDATA #REQUIRED>
<!-- Motif elements --><!ELEMENT motifs (motif)*>
<!ELEMENT motif (scores , probabilities , regular_expression? , contributing_sites)>
<!ATTLIST motif id ID #REQUIRED>
<!ATTLIST motif name CDATA #REQUIRED>
<!ATTLIST motif alt CDATA "">
<!ATTLIST motif width CDATA #REQUIRED>
<!ATTLIST motif sites CDATA #REQUIRED>
<!ATTLIST motif ic CDATA #REQUIRED>
<!ATTLIST motif re CDATA #REQUIRED>
<!ATTLIST motif llr CDATA #REQUIRED>
<!ATTLIST motif p_value CDATA #REQUIRED>
<!ATTLIST motif e_value CDATA #REQUIRED>
<!ATTLIST motif bayes_threshold CDATA #REQUIRED>
<!ATTLIST motif elapsed_time CDATA #REQUIRED>
<!ATTLIST motif url CDATA "">
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>
<!-- Contributing site elements --><!-- Contributing sites are motif occurences found during the motif discovery phase --><!ELEMENT contributing_sites (contributing_site)*>
<!ELEMENT contributing_site (left_flank , site , right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED>
<!ATTLIST contributing_site position CDATA #REQUIRED>
<!ATTLIST contributing_site strand (plus | minus | none) "none">
<!ATTLIST contributing_site pvalue CDATA #REQUIRED>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start --><!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance --><!ELEMENT site (letter_ref)*>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end --><!ELEMENT right_flank (#PCDATA)>
<!-- Scanned site elements --><!-- Scanned sites are motif occurences found during the sequence scan phase --><!ELEMENT scanned_sites_summary (scanned_sites)*>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site)*>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED>
<!ATTLIST scanned_sites pvalue CDATA #REQUIRED>
<!ATTLIST scanned_sites num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site motif_id IDREF #REQUIRED>
<!ATTLIST scanned_site strand (plus | minus | none) "none">
<!ATTLIST scanned_site position CDATA #REQUIRED>
<!ATTLIST scanned_site pvalue CDATA #REQUIRED>
<!-- Utility elements --><!-- A reference to a letter in the alphabet --><!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet --><!ELEMENT alphabet_array (value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>
<!-- A alphabet_matrix contains one alphabet_array for each position in a motif --><!ELEMENT alphabet_matrix (alphabet_array)*>
]>
<!-- Begin document body -->
<MEME version="5.5.5" release="Thu Sep 14 08:48:04 2023 +1000">
  <training_set primary_sequences="data/tmp_memedir/NA_TRUE_FALSE_FALSE_50_30_53_156/USF3.fasta" primary_count="6837" primary_positions="827277" control_sequences="--none--" control_count="0" control_positions="0">
    <alphabet name="DNA" like="dna">
      <letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
      <letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
      <letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
      <letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
      <letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
      <letter id="V" symbol="V" equals="ACG" name="Not T"/>
      <letter id="H" symbol="H" equals="ACT" name="Not G"/>
      <letter id="D" symbol="D" equals="AGT" name="Not C"/>
      <letter id="B" symbol="B" equals="CGT" name="Not A"/>
      <letter id="M" symbol="M" equals="AC" name="Amino"/>
      <letter id="R" symbol="R" equals="AG" name="Purine"/>
      <letter id="W" symbol="W" equals="AT" name="Weak"/>
      <letter id="S" symbol="S" equals="CG" name="Strong"/>
      <letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
      <letter id="K" symbol="K" equals="GT" name="Keto"/>
    </alphabet>
    <letter_frequencies>
      <alphabet_array>
        <value letter_id="A">0.206</value>
        <value letter_id="C">0.295</value>
        <value letter_id="G">0.294</value>
        <value letter_id="T">0.205</value>
      </alphabet_array>
    </letter_frequencies>
  </training_set>
  <model>
    <command_line>meme data/tmp_memedir/NA_TRUE_FALSE_FALSE_50_30_53_156/USF3.fasta -oc data/tmp_memedir/NA_TRUE_FALSE_FALSE_50_30_53_156/USF3 -nmotifs 6 -dna -maxw 30 -p 3 -seed 53 </command_line>
    <host>fedora</host>
    <type>zoops</type>
    <nmotifs>6</nmotifs>
    <evalue_threshold>inf</evalue_threshold>
    <object_function>E-value of product of p-values</object_function>
    <spfun>E-value of product of p-values</spfun>
    <min_width>8</min_width>
    <max_width>30</max_width>
    <wg>11</wg>
    <ws>1</ws>
    <endgaps>yes</endgaps>
    <substring>yes</substring>
    <minsites>2</minsites>
    <maxsites>6837</maxsites>
    <wnsites>0.8</wnsites>
    <spmap>uni</spmap>
    <spfuzz>0.5</spfuzz>
    <prior>dirichlet</prior>
    <beta>0.01</beta>
    <maxiter>50</maxiter>
    <distance>1e-05</distance>
    <num_positions>827277</num_positions>
    <seed>53</seed>
    <hsfrac>0</hsfrac>
    <searchsize>100000</searchsize>
    <maxsize>0</maxsize>
    <norand>no</norand>
    <csites>1000</csites>
    <strands>forward</strands>
    <brief>1000</brief>
    <psp_file/>
    <priors_file/>
    <reason_for_stopping>Stopped because requested number of motifs (6) found.</reason_for_stopping>
    <background_frequencies source="--sequences--" order="0">
      <alphabet_array>
        <value letter_id="A">0.206</value>
        <value letter_id="C">0.295</value>
        <value letter_id="G">0.294</value>
        <value letter_id="T">0.205</value>
      </alphabet_array>
    </background_frequencies>
  </model>
  <motifs>
    <motif id="motif_1" name="NDGVCCACGTGGBC" alt="MEME-1" width="14" sites="6804" ic="15.0" re="14.1" llr="66402" p_value="6.4e-3436" e_value="2.1e-1752" bayes_threshold="8.87847" elapsed_time="98.344160">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">-6</value>
            <value letter_id="C">-16</value>
            <value letter_id="G">7</value>
            <value letter_id="T">17</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">40</value>
            <value letter_id="C">-89</value>
            <value letter_id="G">29</value>
            <value letter_id="T">3</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">5</value>
            <value letter_id="C">-54</value>
            <value letter_id="G">64</value>
            <value letter_id="T">-73</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">53</value>
            <value letter_id="C">49</value>
            <value letter_id="G">-10</value>
            <value letter_id="T">-382</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-212</value>
            <value letter_id="C">139</value>
            <value letter_id="G">-421</value>
            <value letter_id="T">-33</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1938</value>
            <value letter_id="C">176</value>
            <value letter_id="G">-1938</value>
            <value letter_id="T">-1938</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">228</value>
            <value letter_id="C">-1938</value>
            <value letter_id="G">-1938</value>
            <value letter_id="T">-1938</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1938</value>
            <value letter_id="C">176</value>
            <value letter_id="G">-938</value>
            <value letter_id="T">-1938</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-581</value>
            <value letter_id="C">-865</value>
            <value letter_id="G">176</value>
            <value letter_id="T">-764</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1938</value>
            <value letter_id="C">-1938</value>
            <value letter_id="G">-1938</value>
            <value letter_id="T">229</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1938</value>
            <value letter_id="C">-997</value>
            <value letter_id="G">176</value>
            <value letter_id="T">-1938</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-28</value>
            <value letter_id="C">-393</value>
            <value letter_id="G">137</value>
            <value letter_id="T">-199</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-377</value>
            <value letter_id="C">-7</value>
            <value letter_id="G">46</value>
            <value letter_id="T">54</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-76</value>
            <value letter_id="C">67</value>
            <value letter_id="G">-53</value>
            <value letter_id="T">1</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.197237</value>
            <value letter_id="C">0.264256</value>
            <value letter_id="G">0.308054</value>
            <value letter_id="T">0.230453</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.271164</value>
            <value letter_id="C">0.159612</value>
            <value letter_id="G">0.359788</value>
            <value letter_id="T">0.209436</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.213698</value>
            <value letter_id="C">0.202822</value>
            <value letter_id="G">0.459436</value>
            <value letter_id="T">0.124045</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.298060</value>
            <value letter_id="C">0.412698</value>
            <value letter_id="G">0.274691</value>
            <value letter_id="T">0.014550</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.047325</value>
            <value letter_id="C">0.774103</value>
            <value letter_id="G">0.015873</value>
            <value letter_id="T">0.162698</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">1.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">1.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.999559</value>
            <value letter_id="G">0.000441</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.003674</value>
            <value letter_id="C">0.000735</value>
            <value letter_id="G">0.994562</value>
            <value letter_id="T">0.001029</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">1.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000294</value>
            <value letter_id="G">0.999706</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.169900</value>
            <value letter_id="C">0.019400</value>
            <value letter_id="G">0.758965</value>
            <value letter_id="T">0.051734</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.015138</value>
            <value letter_id="C">0.280570</value>
            <value letter_id="G">0.405350</value>
            <value letter_id="T">0.298942</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.121693</value>
            <value letter_id="C">0.468254</value>
            <value letter_id="G">0.203263</value>
            <value letter_id="T">0.206790</value>
          </alphabet_array>
        </alphabet_matrix>
      </probabilities>
      <regular_expression>
[GCT][GAT][GAC][CAG]CCACGTGG[GTC][CTG]
</regular_expression>
      <contributing_sites/>
    </motif>
    <motif id="motif_2" name="CYYGKMMTCCCARMRYKYTGGGAKKMCRRG" alt="MEME-2" width="30" sites="257" ic="37.6" re="37.2" llr="6633" p_value="1.7e-384" e_value="2.5e-234" bayes_threshold="11.9974" elapsed_time="166.943691">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">-314</value>
            <value letter_id="C">161</value>
            <value letter_id="G">-424</value>
            <value letter_id="T">-181</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">69</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">136</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-572</value>
            <value letter_id="C">47</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">152</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-33</value>
            <value letter_id="C">-424</value>
            <value letter_id="G">140</value>
            <value letter_id="T">-213</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-340</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">76</value>
            <value letter_id="T">123</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">119</value>
            <value letter_id="C">74</value>
            <value letter_id="G">-424</value>
            <value letter_id="T">-340</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">130</value>
            <value letter_id="C">72</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">-472</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">-466</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">227</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">165</value>
            <value letter_id="G">-465</value>
            <value letter_id="T">-172</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-414</value>
            <value letter_id="C">169</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">-255</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-472</value>
            <value letter_id="C">170</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">-272</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">223</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">-324</value>
            <value letter_id="T">-1465</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">139</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">64</value>
            <value letter_id="T">-1465</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">120</value>
            <value letter_id="C">71</value>
            <value letter_id="G">-324</value>
            <value letter_id="T">-413</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">113</value>
            <value letter_id="C">-366</value>
            <value letter_id="G">69</value>
            <value letter_id="T">-202</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-182</value>
            <value letter_id="C">65</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">122</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">-466</value>
            <value letter_id="G">79</value>
            <value letter_id="T">122</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-572</value>
            <value letter_id="C">81</value>
            <value letter_id="G">-524</value>
            <value letter_id="T">120</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">-466</value>
            <value letter_id="G">-524</value>
            <value letter_id="T">226</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-373</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">174</value>
            <value letter_id="T">-1465</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">177</value>
            <value letter_id="T">-1465</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-373</value>
            <value letter_id="C">-524</value>
            <value letter_id="G">171</value>
            <value letter_id="T">-372</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">226</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">-424</value>
            <value letter_id="T">-1465</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">-344</value>
            <value letter_id="G">70</value>
            <value letter_id="T">127</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-472</value>
            <value letter_id="C">-466</value>
            <value letter_id="G">64</value>
            <value letter_id="T">135</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">134</value>
            <value letter_id="C">47</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">-155</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1465</value>
            <value letter_id="C">158</value>
            <value letter_id="G">-1465</value>
            <value letter_id="T">-81</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">167</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">20</value>
            <value letter_id="T">-572</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">117</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">83</value>
            <value letter_id="T">-372</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-256</value>
            <value letter_id="C">-1465</value>
            <value letter_id="G">171</value>
            <value letter_id="T">-1465</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.023346</value>
            <value letter_id="C">0.902724</value>
            <value letter_id="G">0.015564</value>
            <value letter_id="T">0.058366</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.474708</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.525292</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.003891</value>
            <value letter_id="C">0.408560</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.587549</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.163424</value>
            <value letter_id="C">0.015564</value>
            <value letter_id="G">0.774319</value>
            <value letter_id="T">0.046693</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.019455</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.498054</value>
            <value letter_id="T">0.482490</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.470817</value>
            <value letter_id="C">0.494163</value>
            <value letter_id="G">0.015564</value>
            <value letter_id="T">0.019455</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.505837</value>
            <value letter_id="C">0.486381</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.007782</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.011673</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.988327</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.926070</value>
            <value letter_id="G">0.011673</value>
            <value letter_id="T">0.062257</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.011673</value>
            <value letter_id="C">0.953307</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.035019</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.007782</value>
            <value letter_id="C">0.961089</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.031128</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.968872</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.031128</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.540856</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.459144</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.474708</value>
            <value letter_id="C">0.482490</value>
            <value letter_id="G">0.031128</value>
            <value letter_id="T">0.011673</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.451362</value>
            <value letter_id="C">0.023346</value>
            <value letter_id="G">0.474708</value>
            <value letter_id="T">0.050584</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.058366</value>
            <value letter_id="C">0.463035</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.478599</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.011673</value>
            <value letter_id="G">0.509728</value>
            <value letter_id="T">0.478599</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.003891</value>
            <value letter_id="C">0.517510</value>
            <value letter_id="G">0.007782</value>
            <value letter_id="T">0.470817</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.011673</value>
            <value letter_id="G">0.007782</value>
            <value letter_id="T">0.980545</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.015564</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.984436</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">1.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.015564</value>
            <value letter_id="C">0.007782</value>
            <value letter_id="G">0.961089</value>
            <value letter_id="T">0.015564</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.984436</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.015564</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.027237</value>
            <value letter_id="G">0.478599</value>
            <value letter_id="T">0.494163</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.007782</value>
            <value letter_id="C">0.011673</value>
            <value letter_id="G">0.459144</value>