<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Document definition -->
<!DOCTYPE MEME [
<!ELEMENT MEME (training_set , model , motifs , scanned_sites_summary?)>
<!ATTLIST MEME version CDATA #REQUIRED>
<!ATTLIST MEME release CDATA #REQUIRED>
<!-- Training-set elements --><!ELEMENT training_set (alphabet , ambigs , sequence* , letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED>
<!ATTLIST training_set primary_count CDATA #REQUIRED>
<!ATTLIST training_set primary_positions CDATA #REQUIRED>
<!ATTLIST training_set control_sequences CDATA "">
<!ATTLIST training_set control_count CDATA "">
<!ATTLIST training_set control_positions CDATA "">
<!ELEMENT alphabet (letter)*>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter)*>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED>
<!ATTLIST sequence name CDATA #REQUIRED>
<!ATTLIST sequence length CDATA #REQUIRED>
<!ATTLIST sequence weight CDATA #REQUIRED>
<!ELEMENT letter_frequencies (alphabet_array)>
<!-- Model elements --><!ELEMENT model (command_line , host , type , nmotifs , evalue_threshold , object_function , spfun , min_width , max_width , wg , ws , endgaps , minsites , maxsites , wnsites , spmap , spfuzz , prior , beta , maxiter , distance , num_positions , seed , hsfrac , searchsize , maxsize , norand , csites , strands , brief , psp_file , priors_file , reason_for_stopping , background_frequencies)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>
<!ATTLIST background_frequencies order CDATA #REQUIRED>
<!-- Motif elements --><!ELEMENT motifs (motif)*>
<!ELEMENT motif (scores , probabilities , regular_expression? , contributing_sites)>
<!ATTLIST motif id ID #REQUIRED>
<!ATTLIST motif name CDATA #REQUIRED>
<!ATTLIST motif alt CDATA "">
<!ATTLIST motif width CDATA #REQUIRED>
<!ATTLIST motif sites CDATA #REQUIRED>
<!ATTLIST motif ic CDATA #REQUIRED>
<!ATTLIST motif re CDATA #REQUIRED>
<!ATTLIST motif llr CDATA #REQUIRED>
<!ATTLIST motif p_value CDATA #REQUIRED>
<!ATTLIST motif e_value CDATA #REQUIRED>
<!ATTLIST motif bayes_threshold CDATA #REQUIRED>
<!ATTLIST motif elapsed_time CDATA #REQUIRED>
<!ATTLIST motif url CDATA "">
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>
<!-- Contributing site elements --><!-- Contributing sites are motif occurences found during the motif discovery phase --><!ELEMENT contributing_sites (contributing_site)*>
<!ELEMENT contributing_site (left_flank , site , right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED>
<!ATTLIST contributing_site position CDATA #REQUIRED>
<!ATTLIST contributing_site strand (plus | minus | none) "none">
<!ATTLIST contributing_site pvalue CDATA #REQUIRED>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start --><!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance --><!ELEMENT site (letter_ref)*>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end --><!ELEMENT right_flank (#PCDATA)>
<!-- Scanned site elements --><!-- Scanned sites are motif occurences found during the sequence scan phase --><!ELEMENT scanned_sites_summary (scanned_sites)*>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site)*>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED>
<!ATTLIST scanned_sites pvalue CDATA #REQUIRED>
<!ATTLIST scanned_sites num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site motif_id IDREF #REQUIRED>
<!ATTLIST scanned_site strand (plus | minus | none) "none">
<!ATTLIST scanned_site position CDATA #REQUIRED>
<!ATTLIST scanned_site pvalue CDATA #REQUIRED>
<!-- Utility elements --><!-- A reference to a letter in the alphabet --><!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet --><!ELEMENT alphabet_array (value)*>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>
<!-- A alphabet_matrix contains one alphabet_array for each position in a motif --><!ELEMENT alphabet_matrix (alphabet_array)*>
]>
<!-- Begin document body -->
<MEME version="5.5.5" release="Thu Sep 14 08:48:04 2023 +1000">
  <training_set primary_sequences="data/tmp_memedir/NA_FALSE_TRUE_FALSE_NA_15_53_116/ZNF518B.fasta" primary_count="4822" primary_positions="583462" control_sequences="--none--" control_count="0" control_positions="0">
    <alphabet name="DNA" like="dna">
      <letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
      <letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
      <letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
      <letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
      <letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
      <letter id="V" symbol="V" equals="ACG" name="Not T"/>
      <letter id="H" symbol="H" equals="ACT" name="Not G"/>
      <letter id="D" symbol="D" equals="AGT" name="Not C"/>
      <letter id="B" symbol="B" equals="CGT" name="Not A"/>
      <letter id="M" symbol="M" equals="AC" name="Amino"/>
      <letter id="R" symbol="R" equals="AG" name="Purine"/>
      <letter id="W" symbol="W" equals="AT" name="Weak"/>
      <letter id="S" symbol="S" equals="CG" name="Strong"/>
      <letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
      <letter id="K" symbol="K" equals="GT" name="Keto"/>
    </alphabet>
    <letter_frequencies>
      <alphabet_array>
        <value letter_id="A">0.276</value>
        <value letter_id="C">0.223</value>
        <value letter_id="G">0.225</value>
        <value letter_id="T">0.276</value>
      </alphabet_array>
    </letter_frequencies>
  </training_set>
  <model>
    <command_line>meme data/tmp_memedir/NA_FALSE_TRUE_FALSE_NA_15_53_116/ZNF518B.fasta -oc data/tmp_memedir/NA_FALSE_TRUE_FALSE_NA_15_53_116/ZNF518B -nmotifs 6 -dna -maxw 15 -p 3 -seed 53 </command_line>
    <host>fedora</host>
    <type>zoops</type>
    <nmotifs>6</nmotifs>
    <evalue_threshold>inf</evalue_threshold>
    <object_function>E-value of product of p-values</object_function>
    <spfun>E-value of product of p-values</spfun>
    <min_width>8</min_width>
    <max_width>15</max_width>
    <wg>11</wg>
    <ws>1</ws>
    <endgaps>yes</endgaps>
    <substring>yes</substring>
    <minsites>2</minsites>
    <maxsites>4822</maxsites>
    <wnsites>0.8</wnsites>
    <spmap>uni</spmap>
    <spfuzz>0.5</spfuzz>
    <prior>dirichlet</prior>
    <beta>0.01</beta>
    <maxiter>50</maxiter>
    <distance>1e-05</distance>
    <num_positions>583462</num_positions>
    <seed>53</seed>
    <hsfrac>0</hsfrac>
    <searchsize>100000</searchsize>
    <maxsize>0</maxsize>
    <norand>no</norand>
    <csites>1000</csites>
    <strands>forward</strands>
    <brief>1000</brief>
    <psp_file/>
    <priors_file/>
    <reason_for_stopping>Stopped because requested number of motifs (6) found.</reason_for_stopping>
    <background_frequencies source="--sequences--" order="0">
      <alphabet_array>
        <value letter_id="A">0.276</value>
        <value letter_id="C">0.223</value>
        <value letter_id="G">0.225</value>
        <value letter_id="T">0.276</value>
      </alphabet_array>
    </background_frequencies>
  </model>
  <motifs>
    <motif id="motif_1" name="NDRTAGANNTCTAYH" alt="MEME-1" width="15" sites="3063" ic="13.1" re="12.8" llr="27191" p_value="3.1e-2002" e_value="7.8e-685" bayes_threshold="9.2997" elapsed_time="58.531694">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">-29</value>
            <value letter_id="C">45</value>
            <value letter_id="G">-49</value>
            <value letter_id="T">16</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">32</value>
            <value letter_id="C">-116</value>
            <value letter_id="G">-1</value>
            <value letter_id="T">27</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">34</value>
            <value letter_id="C">-386</value>
            <value letter_id="G">135</value>
            <value letter_id="T">-218</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1822</value>
            <value letter_id="C">-1822</value>
            <value letter_id="G">-232</value>
            <value letter_id="T">179</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">160</value>
            <value letter_id="C">-1822</value>
            <value letter_id="G">-45</value>
            <value letter_id="T">-1822</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1822</value>
            <value letter_id="C">-1822</value>
            <value letter_id="G">215</value>
            <value letter_id="T">-1822</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">114</value>
            <value letter_id="C">-383</value>
            <value letter_id="G">15</value>
            <value letter_id="T">-113</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">1</value>
            <value letter_id="C">-14</value>
            <value letter_id="G">-24</value>
            <value letter_id="T">26</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">29</value>
            <value letter_id="C">-38</value>
            <value letter_id="G">-9</value>
            <value letter_id="T">2</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-124</value>
            <value letter_id="C">18</value>
            <value letter_id="G">-384</value>
            <value letter_id="T">115</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1822</value>
            <value letter_id="C">217</value>
            <value letter_id="G">-1822</value>
            <value letter_id="T">-1822</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1822</value>
            <value letter_id="C">-65</value>
            <value letter_id="G">-1822</value>
            <value letter_id="T">163</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">179</value>
            <value letter_id="C">-278</value>
            <value letter_id="G">-534</value>
            <value letter_id="T">-582</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-234</value>
            <value letter_id="C">137</value>
            <value letter_id="G">-365</value>
            <value letter_id="T">35</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">26</value>
            <value letter_id="C">-5</value>
            <value letter_id="G">-117</value>
            <value letter_id="T">36</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.226249</value>
            <value letter_id="C">0.304277</value>
            <value letter_id="G">0.159974</value>
            <value letter_id="T">0.309500</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.344107</value>
            <value letter_id="C">0.099576</value>
            <value letter_id="G">0.222658</value>
            <value letter_id="T">0.333660</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.348678</value>
            <value letter_id="C">0.015344</value>
            <value letter_id="G">0.574927</value>
            <value letter_id="T">0.061051</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.045054</value>
            <value letter_id="T">0.954946</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.835129</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.164871</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">1.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.609533</value>
            <value letter_id="C">0.015671</value>
            <value letter_id="G">0.248776</value>
            <value letter_id="T">0.126020</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.278159</value>
            <value letter_id="C">0.201763</value>
            <value letter_id="G">0.190010</value>
            <value letter_id="T">0.330069</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.336925</value>
            <value letter_id="C">0.171074</value>
            <value letter_id="G">0.211231</value>
            <value letter_id="T">0.280770</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.117205</value>
            <value letter_id="C">0.252040</value>
            <value letter_id="G">0.015671</value>
            <value letter_id="T">0.615083</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">1.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.142018</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.857982</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.957231</value>
            <value letter_id="C">0.032321</value>
            <value letter_id="G">0.005550</value>
            <value letter_id="T">0.004897</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.054522</value>
            <value letter_id="C">0.576232</value>
            <value letter_id="G">0.017956</value>
            <value letter_id="T">0.351290</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.331048</value>
            <value letter_id="C">0.214496</value>
            <value letter_id="G">0.099902</value>
            <value letter_id="T">0.354554</value>
          </alphabet_array>
        </alphabet_matrix>
      </probabilities>
      <regular_expression>
[TCA][ATG][GA]TAG[AG][TAC][ATG][TC]CTA[CT][TAC]
</regular_expression>
      <contributing_sites/>
    </motif>
    <motif id="motif_2" name="AACTCTCCACCCCAA" alt="MEME-2" width="15" sites="168" ic="25.8" re="26.1" llr="3038" p_value="4.5e-292" e_value="6.5e-136" bayes_threshold="12.5707" elapsed_time="100.408028">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">184</value>
            <value letter_id="C">-1404</value>
            <value letter_id="G">-424</value>
            <value letter_id="T">-1404</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">181</value>
            <value letter_id="C">-422</value>
            <value letter_id="G">-424</value>
            <value letter_id="T">-553</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-395</value>
            <value letter_id="C">214</value>
            <value letter_id="G">-1404</value>
            <value letter_id="T">-1404</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1404</value>
            <value letter_id="C">-264</value>
            <value letter_id="G">-1404</value>
            <value letter_id="T">180</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1404</value>
            <value letter_id="C">211</value>
            <value letter_id="G">-265</value>
            <value letter_id="T">-553</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-453</value>
            <value letter_id="C">-522</value>
            <value letter_id="G">-1404</value>
            <value letter_id="T">183</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-453</value>
            <value letter_id="C">211</value>
            <value letter_id="G">-365</value>
            <value letter_id="T">-453</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-553</value>
            <value letter_id="C">202</value>
            <value letter_id="G">-1404</value>
            <value letter_id="T">-163</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">183</value>
            <value letter_id="C">-1404</value>
            <value letter_id="G">-365</value>
            <value letter_id="T">-1404</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-553</value>
            <value letter_id="C">207</value>
            <value letter_id="G">-524</value>
            <value letter_id="T">-237</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-273</value>
            <value letter_id="C">206</value>
            <value letter_id="G">-524</value>
            <value letter_id="T">-354</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-353</value>
            <value letter_id="C">209</value>
            <value letter_id="G">-1404</value>
            <value letter_id="T">-321</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-353</value>
            <value letter_id="C">206</value>
            <value letter_id="G">-292</value>
            <value letter_id="T">-395</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">182</value>
            <value letter_id="C">-422</value>
            <value letter_id="G">-424</value>
            <value letter_id="T">-1404</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">181</value>
            <value letter_id="C">-522</value>
            <value letter_id="G">-424</value>
            <value letter_id="T">-453</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">0.988095</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.011905</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.970238</value>
            <value letter_id="C">0.011905</value>
            <value letter_id="G">0.011905</value>
            <value letter_id="T">0.005952</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.017857</value>
            <value letter_id="C">0.982143</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.035714</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.964286</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.958333</value>
            <value letter_id="G">0.035714</value>
            <value letter_id="T">0.005952</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.011905</value>
            <value letter_id="C">0.005952</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.982143</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.011905</value>
            <value letter_id="C">0.958333</value>
            <value letter_id="G">0.017857</value>
            <value letter_id="T">0.011905</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.005952</value>
            <value letter_id="C">0.904762</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.089286</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.982143</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.017857</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.005952</value>
            <value letter_id="C">0.934524</value>
            <value letter_id="G">0.005952</value>
            <value letter_id="T">0.053571</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.041667</value>
            <value letter_id="C">0.928571</value>
            <value letter_id="G">0.005952</value>
            <value letter_id="T">0.023810</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.023810</value>
            <value letter_id="C">0.946429</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.029762</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.023810</value>
            <value letter_id="C">0.928571</value>
            <value letter_id="G">0.029762</value>
            <value letter_id="T">0.017857</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.976190</value>
            <value letter_id="C">0.011905</value>
            <value letter_id="G">0.011905</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.970238</value>
            <value letter_id="C">0.005952</value>
            <value letter_id="G">0.011905</value>
            <value letter_id="T">0.011905</value>
          </alphabet_array>
        </alphabet_matrix>
      </probabilities>
      <regular_expression>
AACTCTCCACCCCAA
</regular_expression>
      <contributing_sites/>
    </motif>
    <motif id="motif_3" name="AGAATRTAYATTCTK" alt="MEME-3" width="15" sites="245" ic="24.4" re="23.3" llr="3955" p_value="8.0e-281" e_value="2.6e-108" bayes_threshold="12.3299" elapsed_time="142.187609">
      <scores>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">186</value>
            <value letter_id="C">-1458</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">-1458</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-156</value>
            <value letter_id="C">-1458</value>
            <value letter_id="G">198</value>
            <value letter_id="T">-376</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">186</value>
            <value letter_id="C">-1458</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">-1458</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">180</value>
            <value letter_id="C">-477</value>
            <value letter_id="G">-278</value>
            <value letter_id="T">-1458</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1458</value>
            <value letter_id="C">-418</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">184</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">79</value>
            <value letter_id="C">-477</value>
            <value letter_id="G">119</value>
            <value letter_id="T">-1458</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-508</value>
            <value letter_id="C">-345</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">181</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">180</value>
            <value letter_id="C">-1458</value>
            <value letter_id="G">-298</value>
            <value letter_id="T">-508</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1458</value>
            <value letter_id="C">109</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">93</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">180</value>
            <value letter_id="C">-377</value>
            <value letter_id="G">-420</value>
            <value letter_id="T">-449</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1458</value>
            <value letter_id="C">-1458</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">186</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1458</value>
            <value letter_id="C">-1458</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">186</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1458</value>
            <value letter_id="C">201</value>
            <value letter_id="G">-420</value>
            <value letter_id="T">-162</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-1458</value>
            <value letter_id="C">-345</value>
            <value letter_id="G">-1458</value>
            <value letter_id="T">183</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">-376</value>
            <value letter_id="C">-1458</value>
            <value letter_id="G">114</value>
            <value letter_id="T">81</value>
          </alphabet_array>
        </alphabet_matrix>
      </scores>
      <probabilities>
        <alphabet_matrix>
          <alphabet_array>
            <value letter_id="A">1.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.093878</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.885714</value>
            <value letter_id="T">0.020408</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">1.000000</value>
            <value letter_id="C">0.000000</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.959184</value>
            <value letter_id="C">0.008163</value>
            <value letter_id="G">0.032653</value>
            <value letter_id="T">0.000000</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.000000</value>
            <value letter_id="C">0.012245</value>
            <value letter_id="G">0.000000</value>
            <value letter_id="T">0.987755</value>
          </alphabet_array>
          <alphabet_array>
            <value letter_id="A">0.477551</value>
            <value letter_id="C">0.008163</value>
            <value letter_id="G">0.514286</value>